/**
 * Real 2024-25 squad data for all 92 English football clubs.
 * Each club maps to 23 players matching the fallbackSquadRoles order:
 * GK, LB, CB, CB, RB, DM, CM, CM, LW, ST, RW, GK, LB, CB, RB, DM, CM, AM, LW, ST, RW, ST, PLAYMAKER
 */
export interface RealPlayer {
  name: string;
  age: number;
}

export const realSquads: Record<string, RealPlayer[]> = {
  // ========== PREMIER LEAGUE (20 clubs) ==========
  'Arsenal': [
    { name: 'David Raya', age: 29 },
    { name: 'Oleksandr Zinchenko', age: 27 },
    { name: 'William Saliba', age: 23 },
    { name: 'Gabriel Magalhães', age: 26 },
    { name: 'Ben White', age: 27 },
    { name: 'Thomas Partey', age: 31 },
    { name: 'Declan Rice', age: 25 },
    { name: 'Martin Ødegaard', age: 25 },
    { name: 'Gabriel Martinelli', age: 23 },
    { name: 'Kai Havertz', age: 25 },
    { name: 'Bukayo Saka', age: 23 },
    { name: 'Neto', age: 35 },
    { name: 'Riccardo Calafiori', age: 22 },
    { name: 'Jakub Kiwior', age: 24 },
    { name: 'Jurriën Timber', age: 23 },
    { name: 'Jorginho', age: 32 },
    { name: 'Mikel Merino', age: 28 },
    { name: 'Fabio Vieira', age: 24 },
    { name: 'Leandro Trossard', age: 29 },
    { name: 'Eddie Nketiah', age: 25 },
    { name: 'Raheem Sterling', age: 29 },
    { name: 'Gabriel Jesus', age: 27 },
    { name: 'Ethan Nwaneri', age: 17 },
  ],
  'Aston Villa': [
    { name: 'Emiliano Martínez', age: 32 },
    { name: 'Lucas Digne', age: 31 },
    { name: 'Pau Torres', age: 27 },
    { name: 'Ezri Konsa', age: 27 },
    { name: 'Matty Cash', age: 27 },
    { name: 'Boubacar Kamara', age: 24 },
    { name: 'Youri Tielemans', age: 27 },
    { name: 'John McGinn', age: 30 },
    { name: 'Leon Bailey', age: 27 },
    { name: 'Ollie Watkins', age: 28 },
    { name: 'Moussa Diaby', age: 25 },
    { name: 'Robin Olsen', age: 34 },
    { name: 'Ian Maatsen', age: 22 },
    { name: 'Diego Carlos', age: 31 },
    { name: 'Lamare Bogarde', age: 19 },
    { name: 'Ross Barkley', age: 30 },
    { name: 'Jacob Ramsey', age: 23 },
    { name: 'Emiliano Buendía', age: 27 },
    { name: 'Jaden Philogene', age: 22 },
    { name: 'Jhon Durán', age: 21 },
    { name: 'Morgan Rogers', age: 22 },
    { name: 'Amadou Onana', age: 23 },
    { name: 'Philippe Coutinho', age: 32 },
  ],
  'Brighton': [
    { name: 'Bart Verbruggen', age: 22 },
    { name: 'Pervis Estupiñán', age: 26 },
    { name: 'Lewis Dunk', age: 32 },
    { name: 'Jan Paul van Hecke', age: 24 },
    { name: 'Tariq Lamptey', age: 24 },
    { name: 'Carlos Baleba', age: 20 },
    { name: 'James Milner', age: 38 },
    { name: 'Pascal Groß', age: 33 },
    { name: 'Kaoru Mitoma', age: 27 },
    { name: 'Danny Welbeck', age: 33 },
    { name: 'Simon Adingra', age: 22 },
    { name: 'Jason Steele', age: 33 },
    { name: 'Jack Hinshelwood', age: 19 },
    { name: 'Igor Julio', age: 26 },
    { name: 'Joel Veltman', age: 32 },
    { name: 'Mats Wieffer', age: 24 },
    { name: 'Yankuba Minteh', age: 20 },
    { name: 'Solly March', age: 30 },
    { name: 'Facundo Buonanotte', age: 19 },
    { name: 'Evan Ferguson', age: 19 },
    { name: 'Brajan Gruda', age: 20 },
    { name: 'João Pedro', age: 22 },
    { name: 'Matt O\'Riley', age: 24 },
  ],
  'Burnley': [
    { name: 'James Trafford', age: 21 },
    { name: 'Charlie Taylor', age: 30 },
    { name: 'Jordan Beyer', age: 24 },
    { name: 'Dara O\'Shea', age: 25 },
    { name: 'Connor Roberts', age: 28 },
    { name: 'Josh Cullen', age: 28 },
    { name: 'Josh Brownhill', age: 28 },
    { name: 'Sander Berge', age: 26 },
    { name: 'Wilson Odobert', age: 19 },
    { name: 'Zeki Amdouni', age: 23 },
    { name: 'Luca Koleosho', age: 20 },
    { name: 'Arijanet Muric', age: 25 },
    { name: 'Ameen Al-Dakhil', age: 22 },
    { name: 'CJ Egan-Riley', age: 21 },
    { name: 'Vitinho', age: 24 },
    { name: 'Hjalmar Ekdal', age: 24 },
    { name: 'Hannibal Mejbri', age: 21 },
    { name: 'Aaron Ramsey', age: 21 },
    { name: 'Dara Costelloe', age: 21 },
    { name: 'Jay Rodriguez', age: 35 },
    { name: 'Nathan Redmond', age: 30 },
    { name: 'Manuel Benson', age: 27 },
    { name: 'Mike Tresor', age: 25 },
  ],
  'Chelsea': [
    { name: 'Robert Sánchez', age: 26 },
    { name: 'Marc Cucurella', age: 26 },
    { name: 'Wesley Fofana', age: 23 },
    { name: 'Levi Colwill', age: 21 },
    { name: 'Reece James', age: 24 },
    { name: 'Moisés Caicedo', age: 23 },
    { name: 'Enzo Fernández', age: 23 },
    { name: 'Romeo Lavia', age: 20 },
    { name: 'Mykhailo Mudryk', age: 23 },
    { name: 'Nicolas Jackson', age: 23 },
    { name: 'Noni Madueke', age: 22 },
    { name: 'Filip Jørgensen', age: 22 },
    { name: 'Ben Chilwell', age: 27 },
    { name: 'Axel Disasi', age: 26 },
    { name: 'Malo Gusto', age: 21 },
    { name: 'Cesare Casadei', age: 21 },
    { name: 'Kiernan Dewsbury-Hall', age: 25 },
    { name: 'Cole Palmer', age: 22 },
    { name: 'Pedro Neto', age: 24 },
    { name: 'Christopher Nkunku', age: 27 },
    { name: 'Jadon Sancho', age: 24 },
    { name: 'Marc Guiu', age: 18 },
    { name: 'Carney Chukwuemeka', age: 20 },
  ],
  'Crystal Palace': [
    { name: 'Dean Henderson', age: 27 },
    { name: 'Tyrick Mitchell', age: 25 },
    { name: 'Marc Guéhi', age: 24 },
    { name: 'Joachim Andersen', age: 28 },
    { name: 'Daniel Muñoz', age: 28 },
    { name: 'Adam Wharton', age: 20 },
    { name: 'Cheick Doucouré', age: 24 },
    { name: 'Will Hughes', age: 29 },
    { name: 'Eberechi Eze', age: 26 },
    { name: 'Jean-Philippe Mateta', age: 27 },
    { name: 'Michael Olise', age: 22 },
    { name: 'Sam Johnstone', age: 31 },
    { name: 'Nathaniel Clyne', age: 33 },
    { name: 'Chris Richards', age: 24 },
    { name: 'Tayo Adaramola', age: 20 },
    { name: 'Naouirou Ahamada', age: 22 },
    { name: 'Jeffrey Schlupp', age: 31 },
    { name: 'Daichi Kamada', age: 28 },
    { name: 'Ismaïla Sarr', age: 26 },
    { name: 'Odsonne Édouard', age: 26 },
    { name: 'Matheus França', age: 20 },
    { name: 'Eddie Nketiah', age: 25 },
    { name: 'Jordan Ayew', age: 32 },
  ],
  'Everton': [
    { name: 'Jordan Pickford', age: 30 },
    { name: 'Vitalii Mykolenko', age: 25 },
    { name: 'James Tarkowski', age: 31 },
    { name: 'Jarrad Branthwaite', age: 22 },
    { name: 'Ashley Young', age: 39 },
    { name: 'Idrissa Gueye', age: 35 },
    { name: 'Abdoulaye Doucouré', age: 31 },
    { name: 'James Garner', age: 23 },
    { name: 'Dwight McNeil', age: 24 },
    { name: 'Dominic Calvert-Lewin', age: 27 },
    { name: 'Jack Harrison', age: 27 },
    { name: 'João Virgínia', age: 24 },
    { name: 'Jake O\'Brien', age: 23 },
    { name: 'Michael Keane', age: 31 },
    { name: 'Seamus Coleman', age: 36 },
    { name: 'Tim Iroegbunam', age: 21 },
    { name: 'Orel Mangala', age: 26 },
    { name: 'Iliman Ndiaye', age: 24 },
    { name: 'Jesper Lindstrøm', age: 24 },
    { name: 'Beto', age: 26 },
    { name: 'Arnaut Danjuma', age: 27 },
    { name: 'Neal Maupay', age: 28 },
    { name: 'Harrison Armstrong', age: 17 },
  ],
  'Fulham': [
    { name: 'Bernd Leno', age: 32 },
    { name: 'Antonee Robinson', age: 27 },
    { name: 'Tim Ream', age: 37 },
    { name: 'Calvin Bassey', age: 24 },
    { name: 'Kenny Tete', age: 28 },
    { name: 'João Palhinha', age: 29 },
    { name: 'Harrison Reed', age: 29 },
    { name: 'Sasa Lukić', age: 28 },
    { name: 'Harry Wilson', age: 27 },
    { name: 'Raúl Jiménez', age: 33 },
    { name: 'Adama Traoré', age: 28 },
    { name: 'Steven Benda', age: 25 },
    { name: 'Joe Bryan', age: 30 },
    { name: 'Issa Diop', age: 27 },
    { name: 'Cédric Soares', age: 33 },
    { name: 'Tom Cairney', age: 33 },
    { name: 'Andreas Pereira', age: 28 },
    { name: 'Emile Smith Rowe', age: 24 },
    { name: 'Alex Iwobi', age: 28 },
    { name: 'Rodrigo Muniz', age: 23 },
    { name: 'Bobby De Cordova-Reid', age: 31 },
    { name: 'Carlos Vinícius', age: 29 },
    { name: 'Willian', age: 36 },
  ],
  'Leeds United': [
    { name: 'Illan Meslier', age: 24 },
    { name: 'Junior Firpo', age: 28 },
    { name: 'Pascal Struijk', age: 25 },
    { name: 'Joe Rodon', age: 26 },
    { name: 'Jayden Bogle', age: 24 },
    { name: 'Ethan Ampadu', age: 24 },
    { name: 'Ilia Gruev', age: 24 },
    { name: 'Glen Kamara', age: 28 },
    { name: 'Willy Gnonto', age: 20 },
    { name: 'Patrick Bamford', age: 31 },
    { name: 'Dan James', age: 27 },
    { name: 'Karl Darlow', age: 33 },
    { name: 'Sam Byram', age: 30 },
    { name: 'Max Wöber', age: 26 },
    { name: 'Connor Roberts', age: 28 },
    { name: 'Joe Rothwell', age: 29 },
    { name: 'Brenden Aaronson', age: 24 },
    { name: 'Georginio Rutter', age: 22 },
    { name: 'Crysencio Summerville', age: 22 },
    { name: 'Joel Piroe', age: 24 },
    { name: 'Jaidon Anthony', age: 24 },
    { name: 'Mateo Joseph', age: 20 },
    { name: 'Archie Gray', age: 18 },
  ],
  'Leicester City': [
    { name: 'Mads Hermansen', age: 24 },
    { name: 'James Justin', age: 26 },
    { name: 'Wout Faes', age: 26 },
    { name: 'Jannik Vestergaard', age: 31 },
    { name: 'Ricardo Pereira', age: 30 },
    { name: 'Wilfred Ndidi', age: 27 },
    { name: 'Kiernan Dewsbury-Hall', age: 25 },
    { name: 'Harry Winks', age: 28 },
    { name: 'Stephy Mavididi', age: 26 },
    { name: 'Jamie Vardy', age: 37 },
    { name: 'Abdul Fatawu', age: 20 },
    { name: 'Danny Ward', age: 31 },
    { name: 'Luke Thomas', age: 23 },
    { name: 'Conor Coady', age: 31 },
    { name: 'Victor Kristiansen', age: 21 },
    { name: 'Boubakary Soumaré', age: 25 },
    { name: 'Oliver Skipp', age: 24 },
    { name: 'Facundo Buonanotte', age: 19 },
    { name: 'Bobby De Cordova-Reid', age: 31 },
    { name: 'Patson Daka', age: 25 },
    { name: 'Kasey McAteer', age: 22 },
    { name: 'Tom Cannon', age: 21 },
    { name: 'Bilal El Khannouss', age: 20 },
  ],
  'Liverpool': [
    { name: 'Alisson Becker', age: 31 },
    { name: 'Andrew Robertson', age: 30 },
    { name: 'Virgil van Dijk', age: 33 },
    { name: 'Ibrahima Konaté', age: 25 },
    { name: 'Trent Alexander-Arnold', age: 26 },
    { name: 'Ryan Gravenberch', age: 22 },
    { name: 'Alexis Mac Allister', age: 25 },
    { name: 'Dominik Szoboszlai', age: 24 },
    { name: 'Luis Díaz', age: 27 },
    { name: 'Darwin Núñez', age: 25 },
    { name: 'Mohamed Salah', age: 32 },
    { name: 'Caoimhín Kelleher', age: 25 },
    { name: 'Kostas Tsimikas', age: 28 },
    { name: 'Jarell Quansah', age: 21 },
    { name: 'Conor Bradley', age: 21 },
    { name: 'Wataru Endō', age: 31 },
    { name: 'Curtis Jones', age: 23 },
    { name: 'Harvey Elliott', age: 21 },
    { name: 'Cody Gakpo', age: 25 },
    { name: 'Diogo Jota', age: 27 },
    { name: 'Federico Chiesa', age: 27 },
    { name: 'Ben Doak', age: 19 },
    { name: 'Stefan Bajčetić', age: 19 },
  ],
  'Manchester City': [
    { name: 'Ederson', age: 31 },
    { name: 'Joško Gvardiol', age: 22 },
    { name: 'Rúben Dias', age: 27 },
    { name: 'Manuel Akanji', age: 29 },
    { name: 'Kyle Walker', age: 34 },
    { name: 'Rodri', age: 28 },
    { name: 'Bernardo Silva', age: 30 },
    { name: 'Kevin De Bruyne', age: 33 },
    { name: 'Jack Grealish', age: 29 },
    { name: 'Erling Haaland', age: 24 },
    { name: 'Phil Foden', age: 24 },
    { name: 'Stefan Ortega', age: 31 },
    { name: 'Nathan Aké', age: 29 },
    { name: 'John Stones', age: 30 },
    { name: 'Rico Lewis', age: 19 },
    { name: 'Mateo Kovačić', age: 30 },
    { name: 'Ilkay Gündogan', age: 33 },
    { name: 'Savinho', age: 20 },
    { name: 'Jeremy Doku', age: 22 },
    { name: 'Julián Álvarez', age: 24 },
    { name: 'Oscar Bobb', age: 21 },
    { name: 'Matheus Nunes', age: 26 },
    { name: 'James McAtee', age: 22 },
  ],
  'Manchester Utd': [
    { name: 'André Onana', age: 28 },
    { name: 'Luke Shaw', age: 29 },
    { name: 'Lisandro Martínez', age: 26 },
    { name: 'Harry Maguire', age: 31 },
    { name: 'Diogo Dalot', age: 25 },
    { name: 'Casemiro', age: 32 },
    { name: 'Bruno Fernandes', age: 30 },
    { name: 'Kobbie Mainoo', age: 19 },
    { name: 'Marcus Rashford', age: 27 },
    { name: 'Rasmus Højlund', age: 21 },
    { name: 'Alejandro Garnacho', age: 20 },
    { name: 'Altay Bayındır', age: 26 },
    { name: 'Tyrell Malacia', age: 25 },
    { name: 'Matthijs de Ligt', age: 25 },
    { name: 'Noussair Mazraoui', age: 27 },
    { name: 'Manuel Ugarte', age: 23 },
    { name: 'Christian Eriksen', age: 32 },
    { name: 'Mason Mount', age: 25 },
    { name: 'Antony', age: 24 },
    { name: 'Joshua Zirkzee', age: 23 },
    { name: 'Amad Diallo', age: 22 },
    { name: 'Scott McTominay', age: 27 },
    { name: 'Toby Collyer', age: 20 },
  ],
  'Newcastle Utd': [
    { name: 'Nick Pope', age: 32 },
    { name: 'Dan Burn', age: 32 },
    { name: 'Sven Botman', age: 24 },
    { name: 'Fabian Schär', age: 32 },
    { name: 'Kieran Trippier', age: 34 },
    { name: 'Bruno Guimarães', age: 27 },
    { name: 'Joelinton', age: 28 },
    { name: 'Sean Longstaff', age: 27 },
    { name: 'Anthony Gordon', age: 23 },
    { name: 'Alexander Isak', age: 25 },
    { name: 'Miguel Almirón', age: 30 },
    { name: 'Martin Dúbravka', age: 35 },
    { name: 'Lewis Hall', age: 20 },
    { name: 'Lloyd Kelly', age: 25 },
    { name: 'Tino Livramento', age: 22 },
    { name: 'Sandro Tonali', age: 24 },
    { name: 'Joe Willock', age: 25 },
    { name: 'Jacob Murphy', age: 29 },
    { name: 'Harvey Barnes', age: 26 },
    { name: 'Callum Wilson', age: 32 },
    { name: 'William Osula', age: 21 },
    { name: 'Matt Ritchie', age: 35 },
    { name: 'Elliot Anderson', age: 22 },
  ],
  'Sheffield Utd': [
    { name: 'Wes Foderingham', age: 33 },
    { name: 'Enda Stevens', age: 34 },
    { name: 'John Egan', age: 31 },
    { name: 'Chris Basham', age: 35 },
    { name: 'George Baldock', age: 31 },
    { name: 'Oliver Norwood', age: 33 },
    { name: 'Gustavo Hamer', age: 27 },
    { name: 'Tom Davies', age: 26 },
    { name: 'Cameron Archer', age: 22 },
    { name: 'Rhian Brewster', age: 24 },
    { name: 'Ben Osborn', age: 30 },
    { name: 'Adam Davies', age: 32 },
    { name: 'Max Lowe', age: 27 },
    { name: 'Anel Ahmedhodžić', age: 25 },
    { name: 'Jayden Bogle', age: 24 },
    { name: 'Vini Souza', age: 25 },
    { name: 'Anis Slimane', age: 23 },
    { name: 'James McAtee', age: 22 },
    { name: 'André Brooks', age: 20 },
    { name: 'William Osula', age: 21 },
    { name: 'Benie Traoré', age: 22 },
    { name: 'Daniel Jebbison', age: 20 },
    { name: 'Ollie McBurnie', age: 28 },
  ],
  'Southampton': [
    { name: 'Alex McCarthy', age: 35 },
    { name: 'Ryan Manning', age: 28 },
    { name: 'Jan Bednarek', age: 28 },
    { name: 'Jack Stephens', age: 30 },
    { name: 'Kyle Walker-Peters', age: 27 },
    { name: 'Flynn Downes', age: 25 },
    { name: 'Joe Aribo', age: 28 },
    { name: 'James Ward-Prowse', age: 29 },
    { name: 'Tyler Dibling', age: 18 },
    { name: 'Adam Armstrong', age: 27 },
    { name: 'Samuel Edozie', age: 21 },
    { name: 'Gavin Bazunu', age: 22 },
    { name: 'Juan Larios', age: 20 },
    { name: 'Taylor Harwood-Bellis', age: 22 },
    { name: 'Yukinari Sugawara', age: 24 },
    { name: 'Mateus Fernandes', age: 20 },
    { name: 'Will Smallbone', age: 24 },
    { name: 'Kamaldeen Sulemana', age: 22 },
    { name: 'Ryan Fraser', age: 30 },
    { name: 'Paul Onuachu', age: 30 },
    { name: 'Ben Brereton Díaz', age: 25 },
    { name: 'Cameron Archer', age: 22 },
    { name: 'Shea Charles', age: 21 },
  ],
  'Tottenham': [
    { name: 'Guglielmo Vicario', age: 27 },
    { name: 'Destiny Udogie', age: 22 },
    { name: 'Cristian Romero', age: 26 },
    { name: 'Micky van de Ven', age: 23 },
    { name: 'Pedro Porro', age: 25 },
    { name: 'Yves Bissouma', age: 28 },
    { name: 'Rodrigo Bentancur', age: 27 },
    { name: 'James Maddison', age: 27 },
    { name: 'Son Heung-min', age: 32 },
    { name: 'Dominic Solanke', age: 26 },
    { name: 'Dejan Kulusevski', age: 24 },
    { name: 'Fraser Forster', age: 36 },
    { name: 'Ben Davies', age: 31 },
    { name: 'Radu Drăgușin', age: 22 },
    { name: 'Emerson Royal', age: 25 },
    { name: 'Pape Matar Sarr', age: 22 },
    { name: 'Oliver Skipp', age: 24 },
    { name: 'Brennan Johnson', age: 23 },
    { name: 'Timo Werner', age: 28 },
    { name: 'Richarlison', age: 27 },
    { name: 'Manor Solomon', age: 25 },
    { name: 'Wilson Odobert', age: 19 },
    { name: 'Lucas Bergvall', age: 18 },
  ],
  'West Brom': [
    { name: 'Alex Palmer', age: 27 },
    { name: 'Conor Townsend', age: 31 },
    { name: 'Semi Ajayi', age: 30 },
    { name: 'Kyle Bartley', age: 33 },
    { name: 'Darnell Furlong', age: 28 },
    { name: 'Jayson Molumby', age: 25 },
    { name: 'Okay Yokuşlu', age: 30 },
    { name: 'John Swift', age: 29 },
    { name: 'Grady Diangana', age: 26 },
    { name: 'Josh Maja', age: 25 },
    { name: 'Karlan Grant', age: 26 },
    { name: 'Josh Griffiths', age: 22 },
    { name: 'Torbjørn Heggem', age: 24 },
    { name: 'Cedric Kipre', age: 27 },
    { name: 'Pipa', age: 26 },
    { name: 'Ousmane Diakité', age: 23 },
    { name: 'Alex Mowatt', age: 29 },
    { name: 'Tom Fellows', age: 21 },
    { name: 'Brandon Thomas-Asante', age: 25 },
    { name: 'Devante Cole', age: 29 },
    { name: 'Mikey Johnston', age: 25 },
    { name: 'Daryl Dike', age: 24 },
    { name: 'Chris Brunt', age: 39 },
  ],
  'West Ham': [
    { name: 'Alphonse Areola', age: 31 },
    { name: 'Aaron Cresswell', age: 34 },
    { name: 'Max Kilman', age: 27 },
    { name: 'Konstantinos Mavropanos', age: 26 },
    { name: 'Vladimir Coufal', age: 32 },
    { name: 'Edson Álvarez', age: 27 },
    { name: 'Tomáš Souček', age: 29 },
    { name: 'Lucas Paquetá', age: 27 },
    { name: 'Mohammed Kudus', age: 24 },
    { name: 'Michail Antonio', age: 34 },
    { name: 'Jarrod Bowen', age: 27 },
    { name: 'Łukasz Fabiański', age: 39 },
    { name: 'Emerson Palmieri', age: 30 },
    { name: 'Jean-Clair Todibo', age: 24 },
    { name: 'Ben Johnson', age: 24 },
    { name: 'Guido Rodríguez', age: 30 },
    { name: 'James Ward-Prowse', age: 29 },
    { name: 'Crysencio Summerville', age: 22 },
    { name: 'Luis Guilherme', age: 18 },
    { name: 'Danny Ings', age: 32 },
    { name: 'Carlos Soler', age: 27 },
    { name: 'Niclas Füllkrug', age: 31 },
    { name: 'Andy Irving', age: 24 },
  ],
  'Wolves': [
    { name: 'José Sá', age: 31 },
    { name: 'Rayan Aït-Nouri', age: 23 },
    { name: 'Craig Dawson', age: 34 },
    { name: 'Santiago Bueno', age: 24 },
    { name: 'Nélson Semedo', age: 30 },
    { name: 'João Gomes', age: 23 },
    { name: 'Mario Lemina', age: 30 },
    { name: 'Tommy Doyle', age: 22 },
    { name: 'Pedro Neto', age: 24 },
    { name: 'Matheus Cunha', age: 25 },
    { name: 'Hwang Hee-chan', age: 28 },
    { name: 'Dan Bentley', age: 31 },
    { name: 'Hugo Bueno', age: 22 },
    { name: 'Toti Gomes', age: 25 },
    { name: 'Matt Doherty', age: 32 },
    { name: 'Boubacar Traoré', age: 23 },
    { name: 'Jean-Ricner Bellegarde', age: 26 },
    { name: 'Pablo Sarabia', age: 32 },
    { name: 'Gonçalo Guedes', age: 27 },
    { name: 'Sasa Kalajdžić', age: 27 },
    { name: 'Carlos Forbs', age: 20 },
    { name: 'Jorgen Strand Larsen', age: 24 },
    { name: 'Rodrigo Gomes', age: 21 },
  ],

  // ========== CHAMPIONSHIP (24 clubs) ==========
  'AFC Bournemouth': [
    { name: 'Neto', age: 35 },
    { name: 'Milos Kerkez', age: 21 },
    { name: 'Illia Zabarnyi', age: 22 },
    { name: 'Chris Mepham', age: 27 },
    { name: 'Adam Smith', age: 33 },
    { name: 'Lewis Cook', age: 27 },
    { name: 'Ryan Christie', age: 29 },
    { name: 'Philip Billing', age: 28 },
    { name: 'Antoine Semenyo', age: 24 },
    { name: 'Dominic Solanke', age: 26 },
    { name: 'Dango Ouattara', age: 22 },
    { name: 'Mark Travers', age: 25 },
    { name: 'Marcos Senesi', age: 27 },
    { name: 'Lloyd Kelly', age: 25 },
    { name: 'Max Aarons', age: 24 },
    { name: 'Tyler Adams', age: 25 },
    { name: 'Alex Scott', age: 21 },
    { name: 'Justin Kluivert', age: 25 },
    { name: 'Luis Sinisterra', age: 25 },
    { name: 'Enes Ünal', age: 27 },
    { name: 'Kieffer Moore', age: 32 },
    { name: 'Evanilson', age: 24 },
    { name: 'Marcus Tavernier', age: 25 },
  ],
  'Barnsley FC': [
    { name: 'Gabriel Slonina', age: 20 },
    { name: 'Barry Cotter', age: 24 },
    { name: 'Mael de Givegney', age: 23 },
    { name: 'Marc Roberts', age: 33 },
    { name: 'Jordan Williams', age: 25 },
    { name: 'Luca Connell', age: 23 },
    { name: 'Herbie Kane', age: 25 },
    { name: 'Adam Phillips', age: 26 },
    { name: 'Fabio Jalo', age: 18 },
    { name: 'Davis Keillor-Dunn', age: 26 },
    { name: 'Max Watters', age: 25 },
    { name: 'Jack Walton', age: 26 },
    { name: 'Ben Radcliffe', age: 21 },
    { name: 'Donovan Sherwin', age: 19 },
    { name: 'Corey O\'Keeffe', age: 26 },
    { name: 'Josh Benson', age: 24 },
    { name: 'Jon Russell', age: 23 },
    { name: 'Cameron Thompson', age: 20 },
    { name: 'Stephen Humphrys', age: 27 },
    { name: 'Sam Cosgrove', age: 28 },
    { name: 'Aiden Marsh', age: 22 },
    { name: 'Andy Dales', age: 28 },
    { name: 'Josh Earl', age: 26 },
  ],
  'Birmingham City FC': [
    { name: 'Ryan Allsop', age: 32 },
    { name: 'Lee Buchanan', age: 23 },
    { name: 'Christoph Klarer', age: 25 },
    { name: 'Krystian Bielik', age: 26 },
    { name: 'Ethan Laird', age: 23 },
    { name: 'Paik Seung-ho', age: 27 },
    { name: 'Marc Leonard', age: 22 },
    { name: 'Alfie May', age: 28 },
    { name: 'Siriki Dembélé', age: 27 },
    { name: 'Jay Stansfield', age: 22 },
    { name: 'Koji Miyoshi', age: 27 },
    { name: 'Bailey Peacock-Farrell', age: 27 },
    { name: 'Alex Cochrane', age: 25 },
    { name: 'Dion Sanderson', age: 24 },
    { name: 'Keshi Anderson', age: 29 },
    { name: 'Jordan James', age: 20 },
    { name: 'Taylor Gardner-Hickman', age: 22 },
    { name: 'Juninho Bacuna', age: 27 },
    { name: 'Luke Harris', age: 19 },
    { name: 'Tomoki Iwata', age: 27 },
    { name: 'Scott Wright', age: 27 },
    { name: 'Emil Hansson', age: 26 },
    { name: 'Willum Willumsson', age: 24 },
  ],
  'Blackburn Rovers FC': [
    { name: 'Aynsley Pears', age: 26 },
    { name: 'Harry Pickering', age: 25 },
    { name: 'Dominic Hyam', age: 28 },
    { name: 'Dan Batth', age: 33 },
    { name: 'Callum Brittain', age: 26 },
    { name: 'Lewis Travis', age: 27 },
    { name: 'John Buckley', age: 24 },
    { name: 'Tyrhys Dolan', age: 22 },
    { name: 'Sammie Szmodics', age: 28 },
    { name: 'Sam Gallagher', age: 28 },
    { name: 'Dilan Markanday', age: 23 },
    { name: 'Balázs Tóth', age: 25 },
    { name: 'James Brown', age: 26 },
    { name: 'Ash Phillips', age: 19 },
    { name: 'Hayden Carter', age: 24 },
    { name: 'Joe Rankin-Costello', age: 25 },
    { name: 'Lewis Baker', age: 29 },
    { name: 'Jake Garrett', age: 21 },
    { name: 'Arnór Sigurdsson', age: 25 },
    { name: 'George Hirst', age: 25 },
    { name: 'Makhtar Gueye', age: 26 },
    { name: 'Andi Weimann', age: 32 },
    { name: 'Adam Wharton', age: 20 },
  ],
  'Brentford FC': [
    { name: 'Mark Flekken', age: 31 },
    { name: 'Rico Henry', age: 27 },
    { name: 'Ethan Pinnock', age: 31 },
    { name: 'Ben Mee', age: 34 },
    { name: 'Kristoffer Ajer', age: 26 },
    { name: 'Christian Nørgaard', age: 30 },
    { name: 'Vitaly Janelt', age: 26 },
    { name: 'Mathias Jensen', age: 28 },
    { name: 'Bryan Mbeumo', age: 25 },
    { name: 'Ivan Toney', age: 28 },
    { name: 'Yoane Wissa', age: 28 },
    { name: 'Thomas Strakosha', age: 29 },
    { name: 'Mads Roerslev', age: 25 },
    { name: 'Zanka', age: 34 },
    { name: 'Aaron Hickey', age: 22 },
    { name: 'Frank Onyeka', age: 26 },
    { name: 'Mikkel Damsgaard', age: 24 },
    { name: 'Keane Lewis-Potter', age: 23 },
    { name: 'Sergi Canós', age: 27 },
    { name: 'Kevin Schade', age: 23 },
    { name: 'Saman Ghoddos', age: 31 },
    { name: 'Igor Thiago', age: 23 },
    { name: 'Fabio Carvalho', age: 22 },
  ],
  'Bristol City FC': [
    { name: 'Max O\'Leary', age: 27 },
    { name: 'Cam Pring', age: 24 },
    { name: 'Rob Dickie', age: 28 },
    { name: 'Kal Naismith', age: 32 },
    { name: 'George Tanner', age: 25 },
    { name: 'Joe Williams', age: 27 },
    { name: 'Jason Knight', age: 23 },
    { name: 'Anis Mehmeti', age: 24 },
    { name: 'Sam Bell', age: 22 },
    { name: 'Nahki Wells', age: 34 },
    { name: 'Fally Mayulu', age: 21 },
    { name: 'Stefan Bajić', age: 22 },
    { name: 'Hayden Roberts', age: 22 },
    { name: 'Zak Vyner', age: 27 },
    { name: 'Ross McCrorie', age: 26 },
    { name: 'Mark Sykes', age: 27 },
    { name: 'Scott Twine', age: 25 },
    { name: 'Tommy Conway', age: 22 },
    { name: 'Sinclair Armstrong', age: 21 },
    { name: 'Andi Weimann', age: 32 },
    { name: 'Yu Hirakawa', age: 23 },
    { name: 'Chris Martin', age: 35 },
    { name: 'Harry Cornick', age: 29 },
  ],
  'Cardiff City FC': [
    { name: 'Ethan Horvath', age: 29 },
    { name: 'Jamilu Collins', age: 29 },
    { name: 'Dimitrios Goutas', age: 29 },
    { name: 'Perry Ng', age: 28 },
    { name: 'Mahlon Romeo', age: 28 },
    { name: 'Manolis Siopis', age: 30 },
    { name: 'Joe Ralls', age: 30 },
    { name: 'Aaron Ramsey', age: 33 },
    { name: 'Ollie Tanner', age: 22 },
    { name: 'Callum Robinson', age: 29 },
    { name: 'Yakou Méïté', age: 28 },
    { name: 'Jak Alnwick', age: 31 },
    { name: 'Callum O\'Dowda', age: 29 },
    { name: 'Mark McGuinness', age: 23 },
    { name: 'Nathaniel Phillips', age: 27 },
    { name: 'Josh Bowler', age: 25 },
    { name: 'Ryan Wintle', age: 27 },
    { name: 'David Turnbull', age: 25 },
    { name: 'Karlan Grant', age: 26 },
    { name: 'Kion Etete', age: 22 },
    { name: 'Wilfried Kanga', age: 26 },
    { name: 'Rubin Colwill', age: 22 },
    { name: 'Isaak Davies', age: 22 },
  ],
  'Coventry City FC': [
    { name: 'Ben Wilson', age: 32 },
    { name: 'Jay Dasilva', age: 26 },
    { name: 'Bobby Thomas', age: 23 },
    { name: 'Luis Binks', age: 23 },
    { name: 'Milan van Ewijk', age: 24 },
    { name: 'Ben Sheaf', age: 27 },
    { name: 'Josh Eccles', age: 24 },
    { name: 'Victor Torp', age: 21 },
    { name: 'Haji Wright', age: 26 },
    { name: 'Ellis Simms', age: 23 },
    { name: 'Jack Rudoni', age: 23 },
    { name: 'Brad Collins', age: 27 },
    { name: 'Jake Bidwell', age: 31 },
    { name: 'Liam Kitching', age: 24 },
    { name: 'Joel Latibeaudiere', age: 24 },
    { name: 'Jamie Allen', age: 29 },
    { name: 'Kasey Palmer', age: 27 },
    { name: 'Tatsuhiro Sakamoto', age: 27 },
    { name: 'Brandon Mason', age: 27 },
    { name: 'Matty Godden', age: 33 },
    { name: 'Ephron Mason-Clark', age: 25 },
    { name: 'Norman Bassette', age: 19 },
    { name: 'Fabio Tavares', age: 23 },
  ],
  'Derby County FC': [
    { name: 'Jacob Widell Zetterström', age: 26 },
    { name: 'Craig Forsyth', age: 35 },
    { name: 'Eiran Cashin', age: 22 },
    { name: 'Curtis Nelson', age: 31 },
    { name: 'Kane Wilson', age: 24 },
    { name: 'Ebou Adams', age: 28 },
    { name: 'David Ozoh', age: 19 },
    { name: 'Ben Osborn', age: 30 },
    { name: 'Tom Barkhuizen', age: 31 },
    { name: 'Jerry Yates', age: 28 },
    { name: 'Nathaniel Mendez-Laing', age: 32 },
    { name: 'Josh Vickers', age: 29 },
    { name: 'Callum Elder', age: 29 },
    { name: 'Sonny Bradley', age: 32 },
    { name: 'Ryan Nyambe', age: 26 },
    { name: 'Kenzo Goudmijn', age: 21 },
    { name: 'Kayden Jackson', age: 29 },
    { name: 'Marcus Harness', age: 28 },
    { name: 'Corey Blackett-Taylor', age: 27 },
    { name: 'James Collins', age: 34 },
    { name: 'Liam Thompson', age: 22 },
    { name: 'Dajaune Brown', age: 19 },
    { name: 'Jake Rooney', age: 19 },
  ],
  'Huddersfield Town AFC': [
    { name: 'Lee Nicholls', age: 32 },
    { name: 'Josh Ruffels', age: 30 },
    { name: 'Michal Helik', age: 29 },
    { name: 'Tom Lees', age: 33 },
    { name: 'Ollie Turton', age: 32 },
    { name: 'Jonathan Hogg', age: 36 },
    { name: 'Ben Wiles', age: 25 },
    { name: 'Antony Evans', age: 25 },
    { name: 'Sorba Thomas', age: 25 },
    { name: 'Danny Ward', age: 33 },
    { name: 'Delano Burgzorg', age: 25 },
    { name: 'Chris Maxwell', age: 34 },
    { name: 'Brodie Spencer', age: 22 },
    { name: 'Nigel Lonwijk', age: 22 },
    { name: 'Lasse Sørensen', age: 24 },
    { name: 'David Kasumu', age: 24 },
    { name: 'Herbie Kane', age: 25 },
    { name: 'Jack Rudoni', age: 23 },
    { name: 'Rhys Healey', age: 29 },
    { name: 'Bojan Radulović', age: 23 },
    { name: 'Jaheim Headley', age: 22 },
    { name: 'Callum Marshall', age: 19 },
    { name: 'Joe Hodge', age: 21 },
  ],
  'Luton Town FC': [
    { name: 'Thomas Kaminski', age: 31 },
    { name: 'Amari\'i Bell', age: 30 },
    { name: 'Tom Lockyer', age: 30 },
    { name: 'Teden Mengi', age: 22 },
    { name: 'James Bree', age: 27 },
    { name: 'Marvelous Nakamba', age: 30 },
    { name: 'Pelly Ruddock Mpanzu', age: 30 },
    { name: 'Jordan Clark', age: 30 },
    { name: 'Chiedozie Ogbene', age: 27 },
    { name: 'Carlton Morris', age: 28 },
    { name: 'Tahith Chong', age: 24 },
    { name: 'Tim Krul', age: 36 },
    { name: 'Dan Potts', age: 30 },
    { name: 'Reece Burke', age: 28 },
    { name: 'Daiki Hashioka', age: 25 },
    { name: 'Albert Sambi Lokonga', age: 25 },
    { name: 'Ross Barkley', age: 30 },
    { name: 'Alfie Doughty', age: 24 },
    { name: 'Jacob Brown', age: 26 },
    { name: 'Elijah Adebayo', age: 26 },
    { name: 'Cauley Woodrow', age: 29 },
    { name: 'Joe Taylor', age: 22 },
    { name: 'Luke Berry', age: 32 },
  ],
  'Middlesbrough FC': [
    { name: 'Seny Dieng', age: 29 },
    { name: 'Lukas Engel', age: 26 },
    { name: 'Rav van den Berg', age: 20 },
    { name: 'Darragh Lenihan', age: 30 },
    { name: 'Tommy Smith', age: 32 },
    { name: 'Aidan Morris', age: 22 },
    { name: 'Hayden Hackney', age: 22 },
    { name: 'Dan Barlaser', age: 27 },
    { name: 'Riley McGree', age: 25 },
    { name: 'Emmanuel Latte Lath', age: 25 },
    { name: 'Isaiah Jones', age: 25 },
    { name: 'Tom Glover', age: 27 },
    { name: 'Alex Bangura', age: 23 },
    { name: 'Matt Clarke', age: 28 },
    { name: 'Luke Ayling', age: 33 },
    { name: 'Jonny Howson', age: 35 },
    { name: 'Marcus Forss', age: 25 },
    { name: 'Finn Azaz', age: 24 },
    { name: 'Ben Doak', age: 19 },
    { name: 'Josh Coburn', age: 22 },
    { name: 'Micah Hamilton', age: 20 },
    { name: 'Morgan Rogers', age: 22 },
    { name: 'Law McCabe', age: 19 },
  ],
  'Millwall FC': [
    { name: 'Matija Šarkić', age: 27 },
    { name: 'Murray Wallace', age: 31 },
    { name: 'Jake Cooper', age: 29 },
    { name: 'Shaun Hutchinson', age: 33 },
    { name: 'Danny McNamara', age: 26 },
    { name: 'George Saville', age: 31 },
    { name: 'Ryan Leonard', age: 32 },
    { name: 'Casper De Norre', age: 27 },
    { name: 'Romain Esse', age: 19 },
    { name: 'Tom Bradshaw', age: 31 },
    { name: 'Zian Flemming', age: 26 },
    { name: 'Bartosz Białkowski', age: 37 },
    { name: 'Aidomo Emakhu', age: 20 },
    { name: 'Japhet Tanganga', age: 25 },
    { name: 'Joe Bryan', age: 30 },
    { name: 'Billy Mitchell', age: 23 },
    { name: 'Duncan Watmore', age: 30 },
    { name: 'Kevin Nisbet', age: 27 },
    { name: 'Tyler Burey', age: 22 },
    { name: 'Macaulay Langstaff', age: 27 },
    { name: 'Femi Azeez', age: 24 },
    { name: 'Josh Coburn', age: 22 },
    { name: 'Bogdan Bogdanović', age: 21 },
  ],
  'Norwich City FC': [
    { name: 'Angus Gunn', age: 28 },
    { name: 'Dimitris Giannoulis', age: 29 },
    { name: 'Ben Gibson', age: 31 },
    { name: 'Shane Duffy', age: 32 },
    { name: 'Ben Chrisene', age: 21 },
    { name: 'Liam Gibbs', age: 21 },
    { name: 'Kenny McLean', age: 32 },
    { name: 'Gabriel Sara', age: 25 },
    { name: 'Borja Sainz', age: 23 },
    { name: 'Ashley Barnes', age: 34 },
    { name: 'Josh Sargent', age: 24 },
    { name: 'George Long', age: 31 },
    { name: 'Sam McCallum', age: 24 },
    { name: 'Andrew Omobamidele', age: 22 },
    { name: 'Grant Hanley', age: 32 },
    { name: 'Jacob Sørensen', age: 26 },
    { name: 'Marcelino Núñez', age: 24 },
    { name: 'Jonathan Rowe', age: 21 },
    { name: 'Abu Kamara', age: 21 },
    { name: 'Adam Idah', age: 23 },
    { name: 'Onel Hernández', age: 31 },
    { name: 'Oscar Schwartau', age: 18 },
    { name: 'Emiliano Buendía', age: 27 },
  ],
  'Nottingham Forest FC': [
    { name: 'Matz Sels', age: 32 },
    { name: 'Nuno Tavares', age: 24 },
    { name: 'Murillo', age: 22 },
    { name: 'Nikola Milenković', age: 27 },
    { name: 'Ola Aina', age: 28 },
    { name: 'Danilo', age: 23 },
    { name: 'Ibrahim Sangaré', age: 26 },
    { name: 'Ryan Yates', age: 27 },
    { name: 'Callum Hudson-Odoi', age: 23 },
    { name: 'Chris Wood', age: 32 },
    { name: 'Anthony Elanga', age: 22 },
    { name: 'Carlos Miguel', age: 25 },
    { name: 'Alex Moreno', age: 31 },
    { name: 'Willy Boly', age: 33 },
    { name: 'Joe Worrall', age: 27 },
    { name: 'Elliot Anderson', age: 22 },
    { name: 'Nicolas Domínguez', age: 26 },
    { name: 'Morgan Gibbs-White', age: 24 },
    { name: 'Jota Silva', age: 25 },
    { name: 'Taiwo Awoniyi', age: 27 },
    { name: 'Ramón Sosa', age: 24 },
    { name: 'Emmanuel Dennis', age: 27 },
    { name: 'James Ward-Prowse', age: 29 },
  ],
  'Preston North End FC': [
    { name: 'Freddie Woodman', age: 27 },
    { name: 'Andrew Hughes', age: 32 },
    { name: 'Liam Lindsay', age: 29 },
    { name: 'Jordan Storey', age: 27 },
    { name: 'Brad Potts', age: 30 },
    { name: 'Alan Browne', age: 29 },
    { name: 'Ali McCann', age: 24 },
    { name: 'Ben Whiteman', age: 28 },
    { name: 'Robbie Brady', age: 32 },
    { name: 'Emil Riis Jakobsen', age: 26 },
    { name: 'Layton Stewart', age: 22 },
    { name: 'Dai Cornell', age: 32 },
    { name: 'Patrick Bauer', age: 32 },
    { name: 'Kian Best', age: 19 },
    { name: 'Duane Holmes', age: 29 },
    { name: 'Stefan Thordarson', age: 22 },
    { name: 'Ryan Ledson', age: 27 },
    { name: 'Jeppe Okkels', age: 24 },
    { name: 'Mads Frokjaer-Jensen', age: 25 },
    { name: 'Will Keane', age: 31 },
    { name: 'Sam Greenwood', age: 22 },
    { name: 'Milutin Osmanković', age: 21 },
    { name: 'Liam Millar', age: 25 },
  ],
  'Queens Park Rangers FC': [
    { name: 'Paul Nardi', age: 30 },
    { name: 'Kenneth Paal', age: 27 },
    { name: 'Jake Clarke-Salter', age: 27 },
    { name: 'Steve Cook', age: 33 },
    { name: 'Jimmy Dunne', age: 27 },
    { name: 'Sam Field', age: 26 },
    { name: 'Stefan Johansen', age: 33 },
    { name: 'Lucas Andersen', age: 29 },
    { name: 'Ilias Chair', age: 26 },
    { name: 'Lyndon Dykes', age: 29 },
    { name: 'Sinclair Armstrong', age: 21 },
    { name: 'Joe Walsh', age: 27 },
    { name: 'Harrison Ashby', age: 22 },
    { name: 'Liam Morrison', age: 22 },
    { name: 'Osman Kakay', age: 26 },
    { name: 'Jack Colback', age: 34 },
    { name: 'André Dozzell', age: 25 },
    { name: 'Karamoko Dembélé', age: 21 },
    { name: 'Nicolas Madsen', age: 27 },
    { name: 'Michael Frey', age: 29 },
    { name: 'Paul Smyth', age: 27 },
    { name: 'Koki Saito', age: 23 },
    { name: 'Morgan Fox', age: 31 },
  ],
  'Reading FC': [
    { name: 'Joel Pereira', age: 29 },
    { name: 'Jeriel Dorsett', age: 26 },
    { name: 'Haydon Roberts', age: 23 },
    { name: 'Paudie O\'Connor', age: 28 },
    { name: 'Andy Yiadom', age: 34 },
    { name: 'Liam Fraser', age: 27 },
    { name: 'Lewis Wing', age: 30 },
    { name: 'Charlie Savage', age: 22 },
    { name: 'Daniel Kyerewaa', age: 22 },
    { name: 'Jack Marriott', age: 31 },
    { name: 'Randell Williams', age: 29 },
    { name: 'Jack Stevens', age: 24 },
    { name: 'Benn Ward', age: 23 },
    { name: 'Derrick Williams', age: 32 },
    { name: 'Ryan Nyambe', age: 28 },
    { name: 'Andy Rinomhota', age: 28 },
    { name: 'Mamadi Camará', age: 24 },
    { name: 'Paddy Lane', age: 23 },
    { name: 'Matt Ritchie', age: 36 },
    { name: 'Kelvin Ehibhatiomhan', age: 22 },
    { name: 'Ben Elliott', age: 25 },
    { name: 'Will Keane', age: 32 },
    { name: 'Kamari Doyle', age: 21 },
  ],
  'Rotherham United FC': [
    { name: 'Cameron Dawson', age: 29 },
    { name: 'Cohen Bramall', age: 28 },
    { name: 'Cameron Humphreys', age: 24 },
    { name: 'Jamie McCart', age: 27 },
    { name: 'Lee Peltier', age: 38 },
    { name: 'Jamie Lindsay', age: 28 },
    { name: 'Dan Barlaser', age: 27 },
    { name: 'Hakeem Odoffin', age: 26 },
    { name: 'Mallik Wilks', age: 25 },
    { name: 'Jordan Hugill', age: 32 },
    { name: 'Jonson Clarke-Harris', age: 30 },
    { name: 'Dillon Phillips', age: 29 },
    { name: 'Joe Mattock', age: 34 },
    { name: 'Sean Morrison', age: 33 },
    { name: 'Kellan Gordon', age: 25 },
    { name: 'Alex MacDonald', age: 24 },
    { name: 'Liam Kelly', age: 28 },
    { name: 'Tom Eaves', age: 32 },
    { name: 'Sebastian Sherwin', age: 19 },
    { name: 'Sam Nombe', age: 24 },
    { name: 'Joseph Hungbo', age: 24 },
    { name: 'Cafu', age: 25 },
    { name: 'Joe Powell', age: 25 },
  ],
  'Sheffield Wednesday FC': [
    { name: 'James Beadle', age: 20 },
    { name: 'Marvin Johnson', age: 33 },
    { name: 'Dominic Iorfa', age: 29 },
    { name: 'Michael Ihiekwe', age: 32 },
    { name: 'Yan Valery', age: 25 },
    { name: 'Barry Bannan', age: 34 },
    { name: 'Liam Palmer', age: 33 },
    { name: 'Will Vaulks', age: 30 },
    { name: 'Anthony Musaba', age: 23 },
    { name: 'Ike Ugbo', age: 25 },
    { name: 'Josh Windass', age: 30 },
    { name: 'Pierce Charles', age: 19 },
    { name: 'Reece James', age: 30 },
    { name: 'Di\'Shon Bernard', age: 24 },
    { name: 'Svante Ingelsson', age: 26 },
    { name: 'Pat Bauer', age: 32 },
    { name: 'Akin Famewo', age: 25 },
    { name: 'Shea Charles', age: 21 },
    { name: 'Jamal Lowe', age: 30 },
    { name: 'Michael Smith', age: 32 },
    { name: 'Djeidi Gassama', age: 19 },
    { name: 'James Beadle', age: 20 },
    { name: 'Tyreeq Bakinson', age: 25 },
  ],
  'Stoke City FC': [
    { name: 'Viktor Johansson', age: 26 },
    { name: 'Enda Stevens', age: 34 },
    { name: 'Ben Wilmot', age: 25 },
    { name: 'Michael Rose', age: 28 },
    { name: 'Junior Tchamadeu', age: 22 },
    { name: 'Josh Laurent', age: 29 },
    { name: 'Jordan Thompson', age: 27 },
    { name: 'Wouter Burger', age: 23 },
    { name: 'Million Manhoef', age: 22 },
    { name: 'Niall Ennis', age: 25 },
    { name: 'Andrew Moran', age: 21 },
    { name: 'Jack Bonham', age: 31 },
    { name: 'Lynden Gooch', age: 28 },
    { name: 'Ashley Phillips', age: 19 },
    { name: 'Ki-Jana Hoever', age: 22 },
    { name: 'Lewis Baker', age: 29 },
    { name: 'Ben Gibson', age: 31 },
    { name: 'Bae Jun-ho', age: 21 },
    { name: 'Bosun Lawal', age: 22 },
    { name: 'Sam Gallagher', age: 28 },
    { name: 'Tatsuki Seko', age: 22 },
    { name: 'Emre Tezgel', age: 19 },
    { name: 'Ryan Mmaee', age: 27 },
  ],
  'Swansea City FC': [
    { name: 'Carl Rushworth', age: 23 },
    { name: 'Josh Tymon', age: 25 },
    { name: 'Harry Darling', age: 25 },
    { name: 'Ben Cabango', age: 24 },
    { name: 'Josh Key', age: 24 },
    { name: 'Jay Fulton', age: 30 },
    { name: 'Matt Grimes', age: 29 },
    { name: 'Joe Allen', age: 34 },
    { name: 'Ronald', age: 24 },
    { name: 'Jerry Yates', age: 28 },
    { name: 'Jamal Lowe', age: 30 },
    { name: 'Andy Fisher', age: 26 },
    { name: 'Nathan Wood', age: 22 },
    { name: 'Kyle Naughton', age: 35 },
    { name: 'Kristian Pedersen', age: 29 },
    { name: 'Azeem Abdulai', age: 19 },
    { name: 'Liam Cullen', age: 25 },
    { name: 'Ollie Cooper', age: 23 },
    { name: 'Eom Ji-sung', age: 25 },
    { name: 'Josh Ginnelly', age: 27 },
    { name: 'Mykola Kukharevych', age: 24 },
    { name: 'Zan Vipotnik', age: 24 },
    { name: 'Jamie Paterson', age: 33 },
  ],
  'Watford FC': [
    { name: 'Daniel Bachmann', age: 30 },
    { name: 'Ryan Porteous', age: 25 },
    { name: 'Francisco Sierralta', age: 27 },
    { name: 'Craig Cathcart', age: 35 },
    { name: 'Jeremy Ngakia', age: 24 },
    { name: 'Tom Cleverley', age: 35 },
    { name: 'Imrân Louza', age: 25 },
    { name: 'Ryan Andrews', age: 22 },
    { name: 'Ken Sema', age: 30 },
    { name: 'Vakoun Bayo', age: 27 },
    { name: 'Kwadwo Baah', age: 22 },
    { name: 'Jonathan Bond', age: 31 },
    { name: 'James Morris', age: 22 },
    { name: 'Mattie Pollock', age: 22 },
    { name: 'Festy Ebosele', age: 22 },
    { name: 'Edo Kayembe', age: 26 },
    { name: 'Yáser Asprilla', age: 20 },
    { name: 'Moussa Sissoko', age: 35 },
    { name: 'Ismael Koné', age: 22 },
    { name: 'Mileta Rajović', age: 25 },
    { name: 'Giorgi Chakvetadze', age: 25 },
    { name: 'Tom Dele-Bashiru', age: 25 },
    { name: 'Joao Pedro', age: 22 },
  ],
  'Wycombe Wanderers FC': [
    { name: 'Max Stryjek', age: 28 },
    { name: 'Joe Jacobson', age: 38 },
    { name: 'Alfie Mawson', age: 30 },
    { name: 'Ryan Tafazolli', age: 33 },
    { name: 'Jack Grimmer', age: 30 },
    { name: 'Matt Bloomfield', age: 38 },
    { name: 'Lewis Wing', age: 29 },
    { name: 'David Wheeler', age: 34 },
    { name: 'Anis Mehmeti', age: 24 },
    { name: 'Brandon Hanlan', age: 27 },
    { name: 'Garath McCleary', age: 37 },
    { name: 'Adam Przybek', age: 26 },
    { name: 'Jordan Obita', age: 31 },
    { name: 'Luke Leahy', age: 31 },
    { name: 'Jason McCarthy', age: 29 },
    { name: 'Daryl Horgan', age: 32 },
    { name: 'Cameron Humphreys', age: 24 },
    { name: 'Dale Taylor', age: 20 },
    { name: 'Danny Freeman', age: 21 },
    { name: 'Richard Kone', age: 22 },
    { name: 'D\'Mani Mellor', age: 23 },
    { name: 'Sam Vokes', age: 34 },
    { name: 'Nick Freeman', age: 26 },
  ],

  // ========== LEAGUE ONE (24 clubs) ==========
  'AFC Wimbledon': [
    { name: 'Nathan Bishop', age: 27 },
    { name: 'Steve Seddon', age: 28 },
    { name: 'Patrick Bauer', age: 33 },
    { name: 'Ryan Johnson', age: 23 },
    { name: 'Nathan Asiimwe', age: 21 },
    { name: 'Sam Hutchinson', age: 35 },
    { name: 'Jake Reeves', age: 32 },
    { name: 'Callum Maycock', age: 25 },
    { name: 'Marcus Browne', age: 26 },
    { name: 'Omar Bugiel', age: 30 },
    { name: 'James Tilley', age: 27 },
    { name: 'Joe McDonnell', age: 32 },
    { name: 'Leo Young', age: 20 },
    { name: 'Isaac Ogundere', age: 22 },
    { name: 'Brodi Hughes', age: 20 },
    { name: 'Myles Hippolyte', age: 29 },
    { name: 'Alistair Smith', age: 24 },
    { name: 'Delano McCoy-Splatt', age: 22 },
    { name: 'Osman Foyo', age: 20 },
    { name: 'Matty Stevens', age: 27 },
    { name: 'Antwoine Hackford', age: 22 },
    { name: 'Ed Leach', age: 21 },
    { name: 'Aron Sasu', age: 20 },
  ],
  'Accrington Stanley FC': [
    { name: 'Michael Kelly', age: 28 },
    { name: 'Freddie Sass', age: 23 },
    { name: 'Farrend Rawson', age: 28 },
    { name: 'Donald Love', age: 28 },
    { name: 'Devon Matthews', age: 22 },
    { name: 'Seamus Conneely', age: 37 },
    { name: 'Conor Grant', age: 28 },
    { name: 'Liam Coyle', age: 25 },
    { name: 'Isaac Sinclair', age: 22 },
    { name: 'Paddy Madden', age: 34 },
    { name: 'Shaun Whalley', age: 37 },
    { name: 'James Rogerson', age: 21 },
    { name: 'Josh Smith', age: 23 },
    { name: 'Connor O\'Brien', age: 22 },
    { name: 'Tyler Walton', age: 22 },
    { name: 'Dan Martin', age: 24 },
    { name: 'Alex Henderson', age: 24 },
    { name: 'Charlie Hall', age: 22 },
    { name: 'Luke Butterfield', age: 23 },
    { name: 'Kelsey Mooney', age: 22 },
    { name: 'Anjola Popoola', age: 21 },
    { name: 'Charlie Brown', age: 22 },
    { name: 'Isaac Heath', age: 21 },
  ],
  'Blackpool FC': [
    { name: 'Bailey Peacock-Farrell', age: 29 },
    { name: 'James Husband', age: 30 },
    { name: 'Oliver Casey', age: 25 },
    { name: 'Fraser Horsfall', age: 28 },
    { name: 'Andy Lyons', age: 25 },
    { name: 'Jordan Brown', age: 24 },
    { name: 'Leighton Clarkson', age: 25 },
    { name: 'Albie Morgan', age: 24 },
    { name: 'CJ Hamilton', age: 29 },
    { name: 'Niall Ennis', age: 25 },
    { name: 'Josh Bowler', age: 26 },
    { name: 'Franco Ravizzoli', age: 25 },
    { name: 'Hayden Coulson', age: 27 },
    { name: 'Michael Ihiekwe', age: 32 },
    { name: 'Reuell Walters', age: 21 },
    { name: 'George Honeyman', age: 30 },
    { name: 'Karoy Anderson', age: 22 },
    { name: 'Ryan Finnigan', age: 22 },
    { name: 'Zac Ashworth', age: 22 },
    { name: 'Ashley Fletcher', age: 29 },
    { name: 'Dale Taylor', age: 22 },
    { name: 'Michael Obafemi', age: 24 },
    { name: 'Tom Bloxham', age: 22 },
  ],
  'Bristol Rovers FC': [
    { name: 'Luke Southwood', age: 28 },
    { name: 'Jack Sparkes', age: 24 },
    { name: 'Alfie Kilgour', age: 25 },
    { name: 'Taylor Moore', age: 28 },
    { name: 'Joel Senior', age: 24 },
    { name: 'Richie Smallwood', age: 34 },
    { name: 'Josh McEachran', age: 28 },
    { name: 'Luke Thomas', age: 26 },
    { name: 'Shaq Forde', age: 22 },
    { name: 'Promise Omochere', age: 25 },
    { name: 'Ellis Harrison', age: 31 },
    { name: 'Brad Young', age: 23 },
    { name: 'Macauley Southam-Hales', age: 27 },
    { name: 'Tom Lockyer', age: 31 },
    { name: 'Clinton Mola', age: 23 },
    { name: 'Ryan De Havilland', age: 24 },
    { name: 'Kane Thompson-Sommers', age: 22 },
    { name: 'Tommy Leigh', age: 24 },
    { name: 'Yusuf Akhamrich', age: 21 },
    { name: 'Joe Quigley', age: 28 },
    { name: 'Fabrizio Cavegn', age: 22 },
    { name: 'Mees Rijks', age: 21 },
    { name: 'Riley Harbottle', age: 20 },
  ],
  'Burton Albion FC': [
    { name: 'Jordan Amissah', age: 24 },
    { name: 'Jack Armer', age: 26 },
    { name: 'Terence Vancooten', age: 28 },
    { name: 'Toby Sibbick', age: 26 },
    { name: 'Udoka Godwin-Malife', age: 27 },
    { name: 'George Evans', age: 28 },
    { name: 'Kegs Chauke', age: 22 },
    { name: 'Charlie Webster', age: 22 },
    { name: 'Fábio Tavares', age: 25 },
    { name: 'Jake Beesley', age: 28 },
    { name: 'Tyrese Shade', age: 24 },
    { name: 'Bradley Collins', age: 27 },
    { name: 'Dylan Williams', age: 21 },
    { name: 'Jasper Moon', age: 24 },
    { name: 'Nick Akoto', age: 27 },
    { name: 'Ciaran Gilligan', age: 22 },
    { name: 'JJ McKiernan', age: 22 },
    { name: 'James Jones', age: 24 },
    { name: 'Julian Larsson', age: 24 },
    { name: 'Millar Matthews-Lewis', age: 22 },
    { name: 'Kain Adom', age: 21 },
    { name: 'Jack Newall', age: 21 },
    { name: 'Andy Cannon', age: 29 },
  ],
  'Charlton Athletic FC': [
    { name: 'Thomas Kaminski', age: 33 },
    { name: 'Amari\'i Bell', age: 31 },
    { name: 'Lloyd Jones', age: 30 },
    { name: 'Conor Coady', age: 32 },
    { name: 'Kayne Ramsay', age: 25 },
    { name: 'Conor Coventry', age: 25 },
    { name: 'Greg Docherty', age: 29 },
    { name: 'Luke Berry', age: 33 },
    { name: 'Miles Leaburn', age: 22 },
    { name: 'Lyndon Dykes', age: 30 },
    { name: 'Tyreece Campbell', age: 26 },
    { name: 'Tiernan Brooks', age: 24 },
    { name: 'Luke Chambers', age: 21 },
    { name: 'Macaulay Gillesphey', age: 29 },
    { name: 'Zach Mitchell', age: 22 },
    { name: 'Joe Rankin-Costello', age: 24 },
    { name: 'Sonny Carey', age: 24 },
    { name: 'Harvey Knibbs', age: 26 },
    { name: 'Jayden Fevrier', age: 24 },
    { name: 'Matt Godden', age: 34 },
    { name: 'Charlie Kelman', age: 23 },
    { name: 'Ibrahim Fullah', age: 20 },
    { name: 'Josh Edwards', age: 24 },
  ],
  'Crewe Alexandra FC': [
    { name: 'Tom Booth', age: 23 },
    { name: 'Reece Hutchinson', age: 25 },
    { name: 'Mickey Demetriou', age: 34 },
    { name: 'James Connolly', age: 23 },
    { name: 'Lewis Billington', age: 24 },
    { name: 'Max Sanders', age: 26 },
    { name: 'Conor Thomas', age: 30 },
    { name: 'Jack Powell', age: 30 },
    { name: 'Shilow Tracey', age: 25 },
    { name: 'Omar Bogle', age: 31 },
    { name: 'Dion Rankine', age: 24 },
    { name: 'Ian Lawlor', age: 30 },
    { name: 'Stan Dancey', age: 21 },
    { name: 'Alfie Pond', age: 21 },
    { name: 'Joel Tabiner', age: 25 },
    { name: 'Matúš Holíček', age: 24 },
    { name: 'Jack Lankester', age: 24 },
    { name: 'Tommi O\'Reilly', age: 22 },
    { name: 'Emre Tezgel', age: 20 },
    { name: 'Louis Moult', age: 33 },
    { name: 'Josh March', age: 27 },
    { name: 'Adrien Thibaut', age: 23 },
    { name: 'Charlie Finney', age: 22 },
  ],
  'Doncaster Rovers FC': [
    { name: 'Zander Clark', age: 33 },
    { name: 'James Maxwell', age: 24 },
    { name: 'Matty Pearson', age: 32 },
    { name: 'Jay McGrath', age: 24 },
    { name: 'Jamie Sterry', age: 30 },
    { name: 'Owen Bailey', age: 24 },
    { name: 'George Broadbent', age: 24 },
    { name: 'Ben Close', age: 29 },
    { name: 'Luke Molyneux', age: 27 },
    { name: 'Brandon Hanlan', age: 28 },
    { name: 'Glenn Middleton', age: 25 },
    { name: 'Thimothée Lo-Tutala', age: 21 },
    { name: 'Jack Senior', age: 28 },
    { name: 'Neill Byrne', age: 33 },
    { name: 'Tom Nixon', age: 22 },
    { name: 'Harry Clifton', age: 27 },
    { name: 'Robbie Gotts', age: 25 },
    { name: 'Elliot Lee', age: 31 },
    { name: 'Jordan Gibson', age: 27 },
    { name: 'Billy Sharp', age: 39 },
    { name: 'Hakeeb Adelakun', age: 29 },
    { name: 'Darren Robinson', age: 22 },
    { name: 'Seán Grehan', age: 22 },
  ],
  'Fleetwood Town FC': [
    { name: 'Jay Lynch', age: 32 },
    { name: 'Denver Hume', age: 27 },
    { name: 'James Bolton', age: 31 },
    { name: 'Rhys Bennett', age: 34 },
    { name: 'Shaun Rooney', age: 29 },
    { name: 'Elliot Bonds', age: 25 },
    { name: 'Matty Virtue', age: 28 },
    { name: 'Jordan Davies', age: 26 },
    { name: 'Ethan Ennis', age: 21 },
    { name: 'James Norwood', age: 35 },
    { name: 'Esapa Osong', age: 20 },
    { name: 'Luke Hewitson', age: 22 },
    { name: 'Mitch Clark', age: 26 },
    { name: 'Finley Potter', age: 22 },
    { name: 'Harrison Holgate', age: 22 },
    { name: 'Harrison Neal', age: 21 },
    { name: 'Mark Helm', age: 23 },
    { name: 'George Morrison', age: 23 },
    { name: 'Lewis McCann', age: 25 },
    { name: 'Ched Evans', age: 37 },
    { name: 'Will Davies', age: 22 },
    { name: 'Ronan Coughlan', age: 28 },
    { name: 'Owen Devonport', age: 20 },
  ],
  'Gillingham FC': [
    { name: 'Glenn Morris', age: 42 },
    { name: 'Max Clark', age: 30 },
    { name: 'Conor Masterson', age: 27 },
    { name: 'Andy Smith', age: 23 },
    { name: 'Remeao Hutton', age: 26 },
    { name: 'Ethan Coleman', age: 22 },
    { name: 'Armani Little', age: 28 },
    { name: 'Jonny Williams', age: 32 },
    { name: 'Aaron Rowe', age: 25 },
    { name: 'Josh Andrews', age: 22 },
    { name: 'Garath McCleary', age: 38 },
    { name: 'Jake Turner', age: 26 },
    { name: 'Shadrach Ogie', age: 24 },
    { name: 'Omar Beckles', age: 34 },
    { name: 'Travis Akomeah', age: 21 },
    { name: 'Robbie McKenzie', age: 29 },
    { name: 'Harry Waldock', age: 22 },
    { name: 'Bradley Dack', age: 32 },
    { name: 'Seb Palmer-Houlden', age: 21 },
    { name: 'Sam Vokes', age: 36 },
    { name: 'Jonny Smith', age: 28 },
    { name: 'Ronan Hale', age: 27 },
    { name: 'Nelson Khumbeni', age: 21 },
  ],
  'Hull City AFC': [
    { name: 'Ivor Pandur', age: 27 },
    { name: 'Ryan Giles', age: 25 },
    { name: 'Charlie Hughes', age: 22 },
    { name: 'Semi Ajayi', age: 32 },
    { name: 'Lewie Coyle', age: 30 },
    { name: 'John Lundstram', age: 31 },
    { name: 'Eliot Matazo', age: 23 },
    { name: 'Matt Crooks', age: 31 },
    { name: 'Liam Millar', age: 25 },
    { name: 'Oli McBurnie', age: 29 },
    { name: 'Mohamed Belloumi', age: 23 },
    { name: 'Dillon Phillips', age: 30 },
    { name: 'Cody Drameh', age: 23 },
    { name: 'John Egan', age: 33 },
    { name: 'Paddy McNair', age: 30 },
    { name: 'Regan Slater', age: 26 },
    { name: 'Amir Hadžiahmetović', age: 28 },
    { name: 'Kieran Dowell', age: 28 },
    { name: 'Lewis Koumas', age: 20 },
    { name: 'Joe Gelhardt', age: 23 },
    { name: 'David Akintola', age: 25 },
    { name: 'Enis Destan', age: 23 },
    { name: 'Darko Gyabi', age: 21 },
  ],
  'Ipswich Town FC': [
    { name: 'Arijanet Muric', age: 25 },
    { name: 'Leif Davis', age: 24 },
    { name: 'Cameron Burgess', age: 29 },
    { name: 'Luke Woolfenden', age: 25 },
    { name: 'Axel Tuanzebe', age: 26 },
    { name: 'Sam Morsy', age: 32 },
    { name: 'Massimo Luongo', age: 31 },
    { name: 'Wes Burns', age: 30 },
    { name: 'Omari Hutchinson', age: 21 },
    { name: 'Liam Delap', age: 21 },
    { name: 'Nathan Broadhead', age: 26 },
    { name: 'Christian Walton', age: 29 },
    { name: 'Janoi Donacien', age: 31 },
    { name: 'George Edmundson', age: 27 },
    { name: 'Harry Clarke', age: 23 },
    { name: 'Jack Taylor', age: 26 },
    { name: 'Kalvin Phillips', age: 29 },
    { name: 'Conor Chaplin', age: 27 },
    { name: 'Jeremy Sarmiento', age: 22 },
    { name: 'Ali Al-Hamadi', age: 23 },
    { name: 'Marcus Harness', age: 28 },
    { name: 'George Hirst', age: 25 },
    { name: 'Sammie Szmodics', age: 28 },
  ],
  'Lincoln City FC': [
    { name: 'George Wickens', age: 24 },
    { name: 'Adam Reach', age: 32 },
    { name: 'Adam Jackson', age: 31 },
    { name: 'Sonny Bradley', age: 34 },
    { name: 'Tendayi Darikwa', age: 34 },
    { name: 'Tom Bayliss', age: 26 },
    { name: 'Conor McGrandles', age: 30 },
    { name: 'Erik Ring', age: 28 },
    { name: 'Reeco Hackett', age: 26 },
    { name: 'James Collins', age: 35 },
    { name: 'Jack Moylan', age: 24 },
    { name: 'Zach Jeacock', age: 23 },
    { name: 'Ryley Towler', age: 23 },
    { name: 'Tom Hamer', age: 26 },
    { name: 'Josh Honohan', age: 24 },
    { name: 'Dom Jefferies', age: 21 },
    { name: 'Ivan Varfolomeev', age: 23 },
    { name: 'Kamil Conteh', age: 22 },
    { name: 'Oscar Thorn', age: 21 },
    { name: 'Ben House', age: 27 },
    { name: 'Alfie Lloyd', age: 21 },
    { name: 'Rob Street', age: 25 },
    { name: 'Freddie Draper', age: 22 },
  ],
  'Milton Keynes Dons FC': [
    { name: 'Craig MacGillivray', age: 32 },
    { name: 'Joe Tomlinson', age: 26 },
    { name: 'Marvin Ekpiteta', age: 30 },
    { name: 'Curtis Nelson', age: 32 },
    { name: 'Gethin Jones', age: 30 },
    { name: 'Liam Kelly', age: 35 },
    { name: 'Alex Gilbey', age: 30 },
    { name: 'Ben Wiles', age: 26 },
    { name: 'Nathaniel Mendez-Laing', age: 33 },
    { name: 'Scott Hogan', age: 33 },
    { name: 'Jonathan Leko', age: 26 },
    { name: 'Connal Trueman', age: 29 },
    { name: 'Kane Wilson', age: 26 },
    { name: 'Luke Offord', age: 26 },
    { name: 'Laurence Maguire', age: 28 },
    { name: 'Jay Matete', age: 25 },
    { name: 'Will Collar', age: 24 },
    { name: 'Daniel Crowley', age: 28 },
    { name: 'Aaron Nemane', age: 27 },
    { name: 'Aaron Collins', age: 28 },
    { name: 'Connor Lemonheigh-Evans', age: 29 },
    { name: 'Callum Paterson', age: 31 },
    { name: 'Rushian Hepburn-Murphy', age: 27 },
  ],
  'Northampton Town FC': [
    { name: 'Lee Burge', age: 32 },
    { name: 'Nesta Guinness-Walker', age: 26 },
    { name: 'Jon Guthrie', age: 33 },
    { name: 'Jordan Willis', age: 31 },
    { name: 'Jack Burroughs', age: 24 },
    { name: 'Dean Campbell', age: 24 },
    { name: 'Cameron McGeehan', age: 30 },
    { name: 'Sam Hoskins', age: 32 },
    { name: 'Kamarai Swyer', age: 22 },
    { name: 'Tom Eaves', age: 33 },
    { name: 'Elliott List', age: 28 },
    { name: 'Theo Avery', age: 22 },
    { name: 'Conor McCarthy', age: 27 },
    { name: 'Elliott Moore', age: 28 },
    { name: 'Joe Wormleighton', age: 22 },
    { name: 'Tyrese Fornah', age: 25 },
    { name: 'Liam Shaw', age: 24 },
    { name: 'Michael Jacobs', age: 34 },
    { name: 'Kyle Edwards', age: 27 },
    { name: 'Jake Evans', age: 22 },
    { name: 'Jack Vale', age: 24 },
    { name: 'Jack Perkins', age: 21 },
    { name: 'Terry Taylor', age: 24 },
  ],
  'Oxford United FC': [
    { name: 'Jamie Cumming', age: 26 },
    { name: 'Greg Leigh', age: 31 },
    { name: 'Michał Helik', age: 30 },
    { name: 'Ciaron Brown', age: 27 },
    { name: 'Sam Long', age: 30 },
    { name: 'Will Vaulks', age: 32 },
    { name: 'Cameron Brannagan', age: 29 },
    { name: 'Brian De Keersmaecker', age: 24 },
    { name: 'Przemysław Płacheta', age: 27 },
    { name: 'Mark Harris', age: 27 },
    { name: 'Siriki Dembélé', age: 29 },
    { name: 'Simon Eastwood', age: 36 },
    { name: 'Jack Currie', age: 23 },
    { name: 'Ben Davies', age: 32 },
    { name: 'Hidde ter Avest', age: 28 },
    { name: 'Yunus Emre Konak', age: 24 },
    { name: 'Tyler Goodrham', age: 23 },
    { name: 'Stanley Mills', age: 22 },
    { name: 'Ole Romeny', age: 24 },
    { name: 'Aidomo Emakhu', age: 22 },
    { name: 'Will Lankshear', age: 21 },
    { name: 'Nik Prelec', age: 23 },
    { name: 'Jamie Donley', age: 20 },
  ],
  'Peterborough United FC': [
    { name: 'Alex Bass', age: 27 },
    { name: 'Rio Adebisi', age: 25 },
    { name: 'Sam Hughes', age: 28 },
    { name: 'Tom Lees', age: 35 },
    { name: 'Carl Johnston', age: 24 },
    { name: 'Archie Collins', age: 25 },
    { name: 'Matthew Garbett', age: 23 },
    { name: 'Brandon Khela', age: 23 },
    { name: 'Cian Hayes', age: 21 },
    { name: 'Abraham Odoh', age: 23 },
    { name: 'Kyrell Lisbie', age: 22 },
    { name: 'Bastian Smith', age: 21 },
    { name: 'George Nevett', age: 21 },
    { name: 'David Okagbue', age: 21 },
    { name: 'Peter Kioso', age: 26 },
    { name: 'Ben Woods', age: 22 },
    { name: 'Donay O\'Brien-Brady', age: 21 },
    { name: 'Patryk Sykut', age: 20 },
    { name: 'Declan Frith', age: 21 },
    { name: 'Jimmy-Jay Morgan', age: 20 },
    { name: 'Harry Leonard', age: 21 },
    { name: 'David Kamara', age: 20 },
    { name: 'Bolu Shofowoke', age: 20 },
  ],
  'Plymouth Argyle FC': [
    { name: 'Conor Hazard', age: 27 },
    { name: 'Jack MacKenzie', age: 26 },
    { name: 'Julio Pleguezuelo', age: 28 },
    { name: 'Brendan Galloway', age: 29 },
    { name: 'Mathias Ross', age: 24 },
    { name: 'Joe Ralls', age: 32 },
    { name: 'Brendan Wiredu', age: 25 },
    { name: 'Caleb Watts', age: 23 },
    { name: 'Xavier Amaechi', age: 24 },
    { name: 'Lorent Tolaj', age: 23 },
    { name: 'Jamie Paterson', age: 34 },
    { name: 'Zak Baker', age: 22 },
    { name: 'Matthew Sorinola', age: 26 },
    { name: 'Alex Mitchell', age: 24 },
    { name: 'Joe Edwards', age: 35 },
    { name: 'Malachi Boateng', age: 22 },
    { name: 'Bradley Ibrahim', age: 20 },
    { name: 'Ayman Benarous', age: 21 },
    { name: 'Owen Dale', age: 27 },
    { name: 'Owen Oseni', age: 21 },
    { name: 'Ronan Curtis', age: 29 },
    { name: 'Aribim Pepple', age: 22 },
    { name: 'Caleb Roberts', age: 21 },
  ],
  'Portsmouth FC': [
    { name: 'Nicolas Schmid', age: 28 },
    { name: 'Connor Ogilvie', age: 29 },
    { name: 'Josh Knight', age: 28 },
    { name: 'Conor Shaughnessy', age: 29 },
    { name: 'Jordan Williams', age: 26 },
    { name: 'Marlon Pack', age: 34 },
    { name: 'Andre Dozzell', age: 26 },
    { name: 'John Swift', age: 30 },
    { name: 'Josh Murphy', age: 30 },
    { name: 'Colby Bishop', age: 29 },
    { name: 'Adrian Segečić', age: 24 },
    { name: 'Josef Bursik', age: 25 },
    { name: 'Ibane Bowat', age: 23 },
    { name: 'Regan Poole', age: 27 },
    { name: 'Zak Swanson', age: 25 },
    { name: 'Ebou Adams', age: 29 },
    { name: 'Luke Le Roux', age: 25 },
    { name: 'Márk Kosznovszky', age: 22 },
    { name: 'Florian Bianchini', age: 24 },
    { name: 'Conor Chaplin', age: 28 },
    { name: 'Keshi Anderson', age: 30 },
    { name: 'Jacob Brown', age: 27 },
    { name: 'Harvey Blair', age: 22 },
  ],
  'Rochdale AFC': [
    { name: 'Oliver Whatmuff', age: 21 },
    { name: 'David Tutonda', age: 31 },
    { name: 'Liam Hogan', age: 36 },
    { name: 'Ethan Ebanks-Landell', age: 33 },
    { name: 'Kyron Gordon', age: 23 },
    { name: 'Ryan East', age: 24 },
    { name: 'Harvey Gilmour', age: 25 },
    { name: 'Joe Pritchard', age: 29 },
    { name: 'Tarryn Allarakhia', age: 29 },
    { name: 'Emmanuel Dieseruvwe', age: 31 },
    { name: 'Luke Hannant', age: 31 },
    { name: 'Tom Myles', age: 27 },
    { name: 'Bryce Hosannah', age: 25 },
    { name: 'Dan Moss', age: 23 },
    { name: 'Tobi Adebayo-Rowling', age: 27 },
    { name: 'Casey Pettit', age: 22 },
    { name: 'Aidan Barlow', age: 24 },
    { name: 'Anthony Gomez Mancini', age: 25 },
    { name: 'Connor McBride', age: 21 },
    { name: 'Devante Rodney', age: 27 },
    { name: 'Tyler Smith', age: 25 },
    { name: 'Manny Duku', age: 27 },
    { name: 'Ian Henderson', age: 40 },
  ],
  'Shrewsbury Town FC': [
    { name: 'Matthew Cox', age: 22 },
    { name: 'Mal Benning', age: 32 },
    { name: 'Tom Anderson', age: 32 },
    { name: 'Will Boyle', age: 30 },
    { name: 'Luca Hoole', age: 23 },
    { name: 'Sam Clucas', age: 35 },
    { name: 'Taylor Perry', age: 24 },
    { name: 'Nick Freeman', age: 29 },
    { name: 'Anthony Scully', age: 26 },
    { name: 'John Marquis', age: 33 },
    { name: 'Tommy McDermott', age: 21 },
    { name: 'Will Brook', age: 22 },
    { name: 'Josh Ruffels', age: 32 },
    { name: 'Sam Stubbs', age: 26 },
    { name: 'Isaac Lee', age: 21 },
    { name: 'Temple Ojinnaka', age: 20 },
    { name: 'Tom Sang', age: 26 },
    { name: 'Isaac England', age: 20 },
    { name: 'Iwan Morgan', age: 21 },
    { name: 'George Lloyd', age: 26 },
    { name: 'Callum Stewart', age: 23 },
    { name: 'Bradley Ihionvien', age: 22 },
    { name: 'Ismeal Kabia', age: 20 },
  ],
  'Sunderland AFC': [
    { name: 'Simon Moore', age: 35 },
    { name: 'Dennis Cirkin', age: 23 },
    { name: 'Daniel Ballard', age: 25 },
    { name: 'Omar Alderete', age: 29 },
    { name: 'Trai Hume', age: 23 },
    { name: 'Granit Xhaka', age: 33 },
    { name: 'Chris Rigg', age: 18 },
    { name: 'Enzo Le Fée', age: 25 },
    { name: 'Romaine Mundle', age: 24 },
    { name: 'Brian Brobbey', age: 23 },
    { name: 'Nilson Angulo', age: 23 },
    { name: 'Robin Roefs', age: 24 },
    { name: 'Reinildo Mandava', age: 31 },
    { name: 'Nordi Mukiele', age: 28 },
    { name: 'Lutsharel Geertruida', age: 25 },
    { name: 'Luke O\'Nien', age: 31 },
    { name: 'Habib Diarra', age: 21 },
    { name: 'Chemsdine Talbi', age: 21 },
    { name: 'Bertrand Traoré', age: 30 },
    { name: 'Wilson Isidor', age: 24 },
    { name: 'Jocelin Ta Bi', age: 21 },
    { name: 'Eliezer Mayenda', age: 21 },
    { name: 'Milan Aleksić', age: 21 },
  ],
  'Swindon Town FC': [
    { name: 'Connor Ripley', age: 32 },
    { name: 'Filozofe Mabete', age: 22 },
    { name: 'Ryan Tafazolli', age: 34 },
    { name: 'Will Wright', age: 28 },
    { name: 'Harrison Minturn', age: 23 },
    { name: 'Ollie Clarke', age: 33 },
    { name: 'James Ball', age: 26 },
    { name: 'Gavin Kilkenny', age: 25 },
    { name: 'James Scanlon', age: 20 },
    { name: 'Harry Smith', age: 30 },
    { name: 'Tom Nichols', age: 32 },
    { name: 'Lewis Ward', age: 28 },
    { name: 'Jamie Knight-Lebel', age: 22 },
    { name: 'Tom Wilson-Brown', age: 22 },
    { name: 'Jake Batty', age: 22 },
    { name: 'Darren Oldaker', age: 28 },
    { name: 'Junior Hoilett', age: 35 },
    { name: 'Billy Bodin', age: 33 },
    { name: 'Danny Butterworth', age: 23 },
    { name: 'Ollie Palmer', age: 33 },
    { name: 'Michael Olakigbe', age: 22 },
    { name: 'Aaron Drinan', age: 27 },
    { name: 'Paul Glatzel', age: 24 },
  ],
  'Wigan Athletic FC': [
    { name: 'Sam Tickle', age: 24 },
    { name: 'Morgan Fox', age: 32 },
    { name: 'Jason Kerr', age: 28 },
    { name: 'Will Aimson', age: 31 },
    { name: 'Isaac Mabaya', age: 21 },
    { name: 'Jensen Weir', age: 23 },
    { name: 'Callum Wright', age: 25 },
    { name: 'Matt Smith', age: 36 },
    { name: 'Dara Costelloe', age: 23 },
    { name: 'Christian Saydee', age: 24 },
    { name: 'Fraser Murray', age: 26 },
    { name: 'Toby Savin', age: 23 },
    { name: 'Steven Sessegnon', age: 25 },
    { name: 'James Carragher', age: 22 },
    { name: 'Jack Hunt', age: 35 },
    { name: 'Owen Moxon', age: 25 },
    { name: 'Babajide Adeeko', age: 21 },
    { name: 'Callum McManaman', age: 34 },
    { name: 'Joseph Hungbo', age: 25 },
    { name: 'Joe Taylor', age: 23 },
    { name: 'Raphael Borges Rodrigues', age: 22 },
    { name: 'Caylan Vickers', age: 22 },
    { name: 'Ryan Trevitt', age: 23 },
  ],

  // ========== LEAGUE TWO (24 clubs) ==========
  'Barrow AFC': [
    { name: 'Wyll Stanway', age: 24 },
    { name: 'Lewis Shipley', age: 25 },
    { name: 'Charlie Raglan', age: 32 },
    { name: 'Niall Canavan', age: 34 },
    { name: 'Angus MacDonald', age: 33 },
    { name: 'Scott Smith', age: 26 },
    { name: 'Sam Foley', age: 39 },
    { name: 'Jack Earing', age: 25 },
    { name: 'Elliot Newby', age: 26 },
    { name: 'Tyler Walker', age: 29 },
    { name: 'Tom Barkhuizen', age: 32 },
    { name: 'Ben Winterbottom', age: 31 },
    { name: 'Ben Jackson', age: 24 },
    { name: 'Joe Anderson', age: 25 },
    { name: 'MJ Williams', age: 29 },
    { name: 'Isaac Fletcher', age: 25 },
    { name: 'Charlie McCann', age: 22 },
    { name: 'Connor Mahoney', age: 28 },
    { name: 'Katia Kouyaté', age: 24 },
    { name: 'Kane Hemmings', age: 33 },
    { name: 'Jovan Malcolm', age: 23 },
    { name: 'Danny Rose', age: 32 },
    { name: 'Rekeem Harper', age: 25 },
  ],
  'Bolton Wanderers FC': [
    { name: 'James Trafford', age: 21 },
    { name: 'Gethin Jones', age: 28 },
    { name: 'Ricardo Santos', age: 29 },
    { name: 'George Johnston', age: 26 },
    { name: 'Conor Bradley', age: 21 },
    { name: 'MJ Williams', age: 29 },
    { name: 'Aaron Morley', age: 24 },
    { name: 'Kyle Dempsey', age: 29 },
    { name: 'Lloyd Isgrove', age: 31 },
    { name: 'Dion Charles', age: 26 },
    { name: 'Dapo Afolayan', age: 27 },
    { name: 'Joel Dixon', age: 30 },
    { name: 'Declan John', age: 28 },
    { name: 'Will Aimson', age: 29 },
    { name: 'Liam Gordon', age: 25 },
    { name: 'George Thomason', age: 24 },
    { name: 'Kieran Sadlier', age: 30 },
    { name: 'Jon Dadi Bodvarsson', age: 32 },
    { name: 'Josh Sheehan', age: 29 },
    { name: 'Elias Kachunga', age: 32 },
    { name: 'Amadou Bakayoko', age: 28 },
    { name: 'Oladapo Afolayan', age: 27 },
    { name: 'Kieran Lee', age: 33 },
  ],
  'Bradford City AFC': [
    { name: 'Sam Walker', age: 34 },
    { name: 'Ibou Touray', age: 28 },
    { name: 'Joe Wright', age: 30 },
    { name: 'Curtis Tilt', age: 34 },
    { name: 'Harrison Ashby', age: 23 },
    { name: 'Max Power', age: 32 },
    { name: 'Lee Evans', age: 31 },
    { name: 'Antoni Sarcevic', age: 33 },
    { name: 'Tyreik Wright', age: 23 },
    { name: 'Stephen Humphrys', age: 28 },
    { name: 'Josh Neufville', age: 23 },
    { name: 'Joe Hilton', age: 25 },
    { name: 'Aden Baldwin', age: 22 },
    { name: 'Matthew Pennington', age: 31 },
    { name: 'Ciarán Kelly', age: 24 },
    { name: 'George Lapslie', age: 28 },
    { name: 'Nick Powell', age: 31 },
    { name: 'Louie Sibley', age: 24 },
    { name: 'Bobby Pointon', age: 22 },
    { name: 'Paul Mullin', age: 31 },
    { name: 'Ethan Wheatley', age: 20 },
    { name: 'Kayden Jackson', age: 31 },
    { name: 'Joe White', age: 22 },
  ],
  'Cambridge United FC': [
    { name: 'Jake Eastwood', age: 29 },
    { name: 'Ben Purrington', age: 29 },
    { name: 'Michael Morrison', age: 37 },
    { name: 'Kelland Watts', age: 25 },
    { name: 'Liam Bennett', age: 28 },
    { name: 'Dominic Ball', age: 30 },
    { name: 'Korey Smith', age: 34 },
    { name: 'Pelly Ruddock Mpanzu', age: 31 },
    { name: 'Sullay Kaikai', age: 30 },
    { name: 'Louis Appéré', age: 25 },
    { name: 'James Brophy', age: 31 },
    { name: 'Ben Hughes', age: 24 },
    { name: 'Zak Bradshaw', age: 23 },
    { name: 'Sean Raggett', age: 32 },
    { name: 'James Gibbons', age: 27 },
    { name: 'Shane McLoughlin', age: 28 },
    { name: 'Ben Knight', age: 23 },
    { name: 'George Hoddle', age: 20 },
    { name: 'Adam Mayor', age: 20 },
    { name: 'Elias Kachunga', age: 33 },
    { name: 'Shayne Lavery', age: 27 },
    { name: 'Elliott Nevitt', age: 26 },
    { name: 'Glenn McConnell', age: 24 },
  ],
  'Carlisle United FC': [
    { name: 'Gabriel Breeze', age: 23 },
    { name: 'Cameron Harper', age: 24 },
    { name: 'Terell Thomas', age: 29 },
    { name: 'Morgan Feeney', age: 25 },
    { name: 'Archie Davies', age: 23 },
    { name: 'Callum Whelan', age: 27 },
    { name: 'Elliot Embleton', age: 25 },
    { name: 'Stephen Wearne', age: 23 },
    { name: 'Junior Luamba', age: 24 },
    { name: 'Georgie Kelly', age: 28 },
    { name: 'David Ajiboye', age: 26 },
    { name: 'Archie Mair', age: 22 },
    { name: 'Ryan Galvin', age: 26 },
    { name: 'Aaron Hayden', age: 28 },
    { name: 'Jack Ellis', age: 22 },
    { name: 'Sam Hetherington', age: 24 },
    { name: 'Alex Gilliead', age: 28 },
    { name: 'Chris Conn-Clarke', age: 23 },
    { name: 'Regan Linney', age: 24 },
    { name: 'Charlie Wyke', age: 33 },
    { name: 'Jordan Jones', age: 30 },
    { name: 'Luke Armstrong', age: 28 },
    { name: 'Ephraim Yeboah', age: 21 },
  ],
  'Cheltenham Town FC': [
    { name: 'Joe Day', age: 35 },
    { name: 'George Harmon', age: 24 },
    { name: 'James Wilson', age: 36 },
    { name: 'Robbie Cundy', age: 27 },
    { name: 'Arkell Jude-Boyd', age: 23 },
    { name: 'Luke Young', age: 32 },
    { name: 'Ben Stevenson', age: 28 },
    { name: 'Ryan Broom', age: 29 },
    { name: 'Jordan Thomas', age: 27 },
    { name: 'George Miller', age: 27 },
    { name: 'Josh Davison', age: 26 },
    { name: 'Mamadou Diallo', age: 22 },
    { name: 'George Nurse', age: 26 },
    { name: 'Sam Sherring', age: 26 },
    { name: 'Jonathan Tomkinson', age: 23 },
    { name: 'Isaac Hutchinson', age: 26 },
    { name: 'Harry Ashfield', age: 22 },
    { name: 'Josh Martin', age: 24 },
    { name: 'Cole Deeming', age: 22 },
    { name: 'Mo Faal', age: 24 },
    { name: 'Jake Bickerstaff', age: 23 },
    { name: 'Tom King', age: 24 },
    { name: 'Sopuruchukwu Obieri', age: 18 },
  ],
  'Colchester United FC': [
    { name: 'Matt Macey', age: 30 },
    { name: 'Ellis Iandolo', age: 25 },
    { name: 'Jack Tucker', age: 24 },
    { name: 'Tom Flanagan', age: 32 },
    { name: 'Rob Hunt', age: 27 },
    { name: 'Dominic Gape', age: 28 },
    { name: 'Teddy Bishop', age: 28 },
    { name: 'Ben Perry', age: 25 },
    { name: 'JK Gordon', age: 23 },
    { name: 'Samson Tovide', age: 24 },
    { name: 'Harry Anderson', age: 28 },
    { name: 'Tom Smith', age: 23 },
    { name: 'Kane Vincent-Young', age: 28 },
    { name: 'Jack Baldwin', age: 31 },
    { name: 'Fin Back', age: 22 },
    { name: 'Arthur Read', age: 24 },
    { name: 'Owura Edwards', age: 25 },
    { name: 'Jack Payne', age: 30 },
    { name: 'Kyreece Lisbie', age: 22 },
    { name: 'Will Goodwin', age: 24 },
    { name: 'Jaden Williams', age: 21 },
    { name: 'Micah Mbick', age: 21 },
    { name: 'Finley Barbrook', age: 20 },
  ],
  'Crawley Town FC': [
    { name: 'Jojo Wollacott', age: 29 },
    { name: 'Scott Malone', age: 34 },
    { name: 'Dion Conroy', age: 30 },
    { name: 'Charlie Barker', age: 23 },
    { name: 'Jay Williams', age: 30 },
    { name: 'Max Anderson', age: 23 },
    { name: 'Reece Brown', age: 29 },
    { name: 'Harry Forster', age: 24 },
    { name: 'Dion Pereira', age: 25 },
    { name: 'Danilo Orsi', age: 28 },
    { name: 'Harry McKirdy', age: 28 },
    { name: 'Jacob Chapman', age: 23 },
    { name: 'Akin Odimayo', age: 24 },
    { name: 'Ben Radcliffe', age: 22 },
    { name: 'Kellan Gordon', age: 27 },
    { name: 'Louie Watson', age: 23 },
    { name: 'Justin Ferizaj', age: 21 },
    { name: 'Taylor Richards', age: 24 },
    { name: 'Ronan Darcy', age: 24 },
    { name: 'Ryan Loft', age: 28 },
    { name: 'Ade Adeyemo', age: 22 },
    { name: 'Tobi Adeyemo', age: 20 },
    { name: 'Louie Copley', age: 20 },
  ],
  'Exeter City FC': [
    { name: 'Joe Whitworth', age: 21 },
    { name: 'Danny Andrew', age: 35 },
    { name: 'Jack Fitzwater', age: 28 },
    { name: 'Ed Turns', age: 24 },
    { name: 'Jack McMillan', age: 26 },
    { name: 'Reece Cole', age: 28 },
    { name: 'Jake Doyle-Hayes', age: 27 },
    { name: 'Ilmari Niskanen', age: 26 },
    { name: 'Carlos Mendes Gomes', age: 27 },
    { name: 'Josh Magennis', age: 35 },
    { name: 'Jack Aitchison', age: 25 },
    { name: 'Jack Bycroft', age: 22 },
    { name: 'Ryan Rydel', age: 25 },
    { name: 'Pierce Sweeney', age: 31 },
    { name: 'Johnly Yfeko', age: 22 },
    { name: 'Kevin McDonald', age: 37 },
    { name: 'Ethan Brierley', age: 21 },
    { name: 'Tom Dean', age: 22 },
    { name: 'Andrew Oluwabori', age: 24 },
    { name: 'Jayden Wareham', age: 21 },
    { name: 'Akeel Higgins', age: 21 },
    { name: 'Sonny Cox', age: 20 },
    { name: 'Timur Tutierov', age: 21 },
  ],
  'Forest Green Rovers FC': [
    { name: 'Luke McNicholas', age: 26 },
    { name: 'Neil Kengni', age: 23 },
    { name: 'Ryan Inniss', age: 30 },
    { name: 'Cian Harries', age: 27 },
    { name: 'Sean Long', age: 30 },
    { name: 'Jay Mingi', age: 24 },
    { name: 'Nick Haughton', age: 31 },
    { name: 'Liam Sercombe', age: 35 },
    { name: 'Tom Knowles', age: 26 },
    { name: 'Christian Doidge', age: 32 },
    { name: 'Kyle McAllister', age: 26 },
    { name: 'Fiachra Pagel', age: 23 },
    { name: 'Laurent Mendy', age: 25 },
    { name: 'Jordan Moore-Taylor', age: 32 },
    { name: 'Harvey Bunker', age: 22 },
    { name: 'Jayden Clarke', age: 22 },
    { name: 'Tre Pemberton', age: 22 },
    { name: 'Tate Campbell', age: 21 },
    { name: 'D\'Mani Mellor', age: 24 },
    { name: 'Kairo Mitchell', age: 28 },
    { name: 'Yahya Bamba', age: 22 },
    { name: 'Temi Babalola', age: 21 },
    { name: 'Max Robson', age: 21 },
  ],
  'Grimsby Town FC': [
    { name: 'Christy Pym', age: 30 },
    { name: 'Jayden Sweeney', age: 22 },
    { name: 'Harvey Rodgers', age: 26 },
    { name: 'Samuel Lavelle', age: 28 },
    { name: 'Maldini Kacurri', age: 24 },
    { name: 'Kieran Green', age: 27 },
    { name: 'Evan Khouri', age: 25 },
    { name: 'Jamie Walker', age: 32 },
    { name: 'Darragh Burns', age: 22 },
    { name: 'Jaze Kabia', age: 26 },
    { name: 'Jason Daði Svanþórsson', age: 28 },
    { name: 'Jackson Smith', age: 22 },
    { name: 'Cameron McJannet', age: 28 },
    { name: 'Tyrell Warren', age: 24 },
    { name: 'Doug Tharme', age: 24 },
    { name: 'George McEachran', age: 23 },
    { name: 'Géza Dávid Turi', age: 25 },
    { name: 'Clarke Oduor', age: 25 },
    { name: 'Justin Amaluzor', age: 28 },
    { name: 'Jude Soonsup-Bell', age: 22 },
    { name: 'Charles Vernam', age: 27 },
    { name: 'Andy Cook', age: 34 },
    { name: 'Fortune Onoh', age: 20 },
  ],
  'Harrogate Town AFC': [
    { name: 'Mark Oxley', age: 35 },
    { name: 'Liam Gibson', age: 28 },
    { name: 'Tom Bradbury', age: 26 },
    { name: 'Warren Burrell', age: 31 },
    { name: 'Zico Asare', age: 24 },
    { name: 'Bryn Morris', age: 29 },
    { name: 'George Thomson', age: 31 },
    { name: 'Jack Evans', age: 26 },
    { name: 'Stephen Duke-McKenna', age: 25 },
    { name: 'Shawn McCoulsky', age: 28 },
    { name: 'Conor McAleny', age: 33 },
    { name: 'Henry Gray', age: 22 },
    { name: 'Jacob Slater', age: 21 },
    { name: 'Anthony O\'Connor', age: 33 },
    { name: 'Lewis Cass', age: 25 },
    { name: 'Josh Falkingham', age: 35 },
    { name: 'Levi Sutton', age: 28 },
    { name: 'Mason Bennett', age: 29 },
    { name: 'Emile Acquah', age: 22 },
    { name: 'Jack Muldoon', age: 36 },
    { name: 'Kaiyne Woolery', age: 30 },
    { name: 'Aiden Marsh', age: 21 },
    { name: 'Tom Hill', age: 23 },
  ],
  'Leyton Orient FC': [
    { name: 'Daniel Bachmann', age: 31 },
    { name: 'James Morris', age: 25 },
    { name: 'Dan Happe', age: 25 },
    { name: 'Jack Simpson', age: 27 },
    { name: 'Tom James', age: 28 },
    { name: 'Tyreeq Bakinson', age: 26 },
    { name: 'Idris El Mizouni', age: 24 },
    { name: 'Dylan Levitt', age: 24 },
    { name: 'Demetri Mitchell', age: 27 },
    { name: 'Aaron Connolly', age: 25 },
    { name: 'Josh Koroma', age: 26 },
    { name: 'Tobi Oluwayemi', age: 23 },
    { name: 'Sean Clare', age: 28 },
    { name: 'Will Forrester', age: 25 },
    { name: 'Rarmani Edmonds-Green', age: 26 },
    { name: 'Michael Craig', age: 22 },
    { name: 'Ollie O\'Neill', age: 22 },
    { name: 'Sonny Perkins', age: 21 },
    { name: 'Theo Archibald', age: 25 },
    { name: 'Dom Ballard', age: 20 },
    { name: 'Charlie Wellens', age: 23 },
    { name: 'Ajay Matthews', age: 22 },
    { name: 'Lemar Gordon', age: 21 },
  ],
  'Mansfield Town FC': [
    { name: 'Liam Roberts', age: 31 },
    { name: 'Stephen McLaughlin', age: 35 },
    { name: 'Ryan Sweeney', age: 28 },
    { name: 'Baily Cargill', age: 30 },
    { name: 'Kyle Knoyle', age: 29 },
    { name: 'Louis Reed', age: 28 },
    { name: 'George Maris', age: 29 },
    { name: 'Aaron Lewis', age: 26 },
    { name: 'Will Evans', age: 28 },
    { name: 'Jordan Bowery', age: 34 },
    { name: 'Lucas Akins', age: 36 },
    { name: 'Owen Mason', age: 22 },
    { name: 'Elliott Hewitt', age: 31 },
    { name: 'Deji Oshilaja', age: 32 },
    { name: 'Frazer Blake-Tracy', age: 28 },
    { name: 'Jon Russell', age: 24 },
    { name: 'Regan Hendry', age: 27 },
    { name: 'Nathan Moriah-Welsh', age: 24 },
    { name: 'Rhys Oates', age: 31 },
    { name: 'Victor Adeboyejo', age: 27 },
    { name: 'Tyler Roberts', age: 26 },
    { name: 'Dom Dwyer', age: 35 },
    { name: 'Max Dickov', age: 20 },
  ],
  'Morecambe FC': [
    { name: 'Jamal Blackman', age: 32 },
    { name: 'Lewis Payne', age: 23 },
    { name: 'Harlee Dean', age: 34 },
    { name: 'Ludwig Francillette', age: 25 },
    { name: 'Raheem Conte', age: 24 },
    { name: 'Yann Songo\'o', age: 33 },
    { name: 'Miguel Azeez', age: 22 },
    { name: 'Jake Cain', age: 24 },
    { name: 'Gwion Edwards', age: 31 },
    { name: 'Harry Panayiotou', age: 28 },
    { name: 'Admiral Muskwe', age: 26 },
    { name: 'Alfie Scales', age: 22 },
    { name: 'Tommy Fogarty', age: 23 },
    { name: 'Liam Hogan', age: 33 },
    { name: 'Ben Williams', age: 26 },
    { name: 'Paul Lewis', age: 28 },
    { name: 'Mohammed Sangare', age: 23 },
    { name: 'George Thomas', age: 28 },
    { name: 'Ben Tollitt', age: 30 },
    { name: 'Joe Nuttall', age: 26 },
    { name: 'Josh Eppiah', age: 23 },
    { name: 'Daniel Ogwuru', age: 22 },
    { name: 'Ma\'kel Campbell', age: 20 },
  ],
  'Newport County AFC': [
    { name: 'Shaun MacDonald', age: 27 },
    { name: 'Anthony Glennon', age: 25 },
    { name: 'Matt Baker', age: 29 },
    { name: 'Ciarán Brennan', age: 24 },
    { name: 'Cameron Evans', age: 25 },
    { name: 'Sven Sprangler', age: 25 },
    { name: 'Matthew Smith', age: 26 },
    { name: 'Harrison Biggins', age: 27 },
    { name: 'Bobby Kamwa', age: 24 },
    { name: 'Courtney Baker-Richardson', age: 30 },
    { name: 'Cole Jarvis', age: 22 },
    { name: 'Jordan Wright', age: 27 },
    { name: 'Liam Shephard', age: 31 },
    { name: 'Ryan Delaney', age: 28 },
    { name: 'Tom Davies', age: 26 },
    { name: 'Joe Thomas', age: 24 },
    { name: 'Ben Lloyd', age: 22 },
    { name: 'Nelson Sanca', age: 25 },
    { name: 'Lewis Jamieson', age: 23 },
    { name: 'Ged Garner', age: 27 },
    { name: 'James Crole', age: 23 },
    { name: 'Nathan Opoku', age: 22 },
    { name: 'Michael Spellman', age: 23 },
  ],
  'Oldham Athletic AFC': [
    { name: 'Mathew Hudson', age: 28 },
    { name: 'Jamie Robson', age: 27 },
    { name: 'Donervon Daniels', age: 31 },
    { name: 'Manny Monthé', age: 30 },
    { name: 'Reagan Ogle', age: 28 },
    { name: 'Ryan Woods', age: 32 },
    { name: 'Tom Conlon', age: 29 },
    { name: 'Tom Pett', age: 33 },
    { name: 'Jack Stevens', age: 25 },
    { name: 'Mike Fondop', age: 30 },
    { name: 'Kane Taylor', age: 23 },
    { name: 'Tom Donaghy', age: 25 },
    { name: 'Jake Leake', age: 25 },
    { name: 'Dynel Simeu', age: 24 },
    { name: 'Jake Caprice', age: 31 },
    { name: 'Josh Hawkes', age: 27 },
    { name: 'Oli Hammond', age: 22 },
    { name: 'Kai Payne', age: 21 },
    { name: 'Fábio Jaló', age: 21 },
    { name: 'Joe Garner', age: 37 },
    { name: 'Kane Drummond', age: 26 },
    { name: 'Calum Kavanagh', age: 22 },
    { name: 'Michael Mellon', age: 22 },
  ],
  'Port Vale FC': [
    { name: 'Ben Amos', age: 35 },
    { name: 'Jaheim Headley', age: 24 },
    { name: 'Ben Heneghan', age: 31 },
    { name: 'Connor Hall', age: 27 },
    { name: 'Jordan Gabriel', age: 26 },
    { name: 'Funso Ojo', age: 32 },
    { name: 'Ben Garrity', age: 27 },
    { name: 'George Byers', age: 28 },
    { name: 'Onel Hernández', age: 32 },
    { name: 'Jayden Stockley', age: 31 },
    { name: 'Ethon Archer', age: 22 },
    { name: 'Joe Gauci', age: 25 },
    { name: 'Liam Gordon', age: 26 },
    { name: 'Tyler Magloire', age: 26 },
    { name: 'Kyle John', age: 24 },
    { name: 'Ryan Croasdale', age: 28 },
    { name: 'Jordan Shipley', age: 28 },
    { name: 'George Hall', age: 21 },
    { name: 'Grant Ward', age: 30 },
    { name: 'Ben Waine', age: 26 },
    { name: 'Dajaune Brown', age: 21 },
    { name: 'Andre Gray', age: 34 },
    { name: 'Martin Sherif', age: 23 },
  ],
  'Salford City FC': [
    { name: 'Matthew Young', age: 25 },
    { name: 'Luke Garbutt', age: 32 },
    { name: 'Michael Rose', age: 29 },
    { name: 'Ollie Turton', age: 30 },
    { name: 'Tom Edwards', age: 26 },
    { name: 'Matt Butcher', age: 27 },
    { name: 'Jorge Grant', age: 29 },
    { name: 'Ben Woodburn', age: 25 },
    { name: 'Kadeem Harris', age: 31 },
    { name: 'Cole Stockton', age: 31 },
    { name: 'Jay Bird', age: 22 },
    { name: 'Mark Howard', age: 39 },
    { name: 'Rosaire Longelo', age: 26 },
    { name: 'Zach Awe', age: 24 },
    { name: 'Loick Ayina', age: 24 },
    { name: 'Ossama Ashley', age: 25 },
    { name: 'Kelly N\'Mai', age: 22 },
    { name: 'Dan Chesters', age: 24 },
    { name: 'Ryan Graydon', age: 27 },
    { name: 'Fabio Borini', age: 34 },
    { name: 'Kallum Cesay', age: 22 },
    { name: 'Daniel Udoh', age: 28 },
    { name: 'Nicolás Siri', age: 23 },
  ],
  'Scunthorpe United FC': [
    { name: 'Maison Campbell', age: 25 },
    { name: 'Branden Horton', age: 27 },
    { name: 'Will Evans', age: 28 },
    { name: 'Andrew Boyce', age: 34 },
    { name: 'Oliver Rose', age: 24 },
    { name: 'Alfie Beestin', age: 26 },
    { name: 'Callum Roberts', age: 27 },
    { name: 'Joe Rowley', age: 25 },
    { name: 'Carlton Ubaezuonu', age: 23 },
    { name: 'Danny Whitehall', age: 30 },
    { name: 'Declan Howe', age: 24 },
    { name: 'Kian Johnson', age: 22 },
    { name: 'Tyler Denton', age: 26 },
    { name: 'Jéan Belehouan', age: 24 },
    { name: 'Ross Barrows', age: 25 },
    { name: 'Kian Scales', age: 24 },
    { name: 'Joey Dawson', age: 23 },
    { name: 'Zain Westbrooke', age: 27 },
    { name: 'Dubem Eze', age: 22 },
    { name: 'Mark Beck', age: 31 },
    { name: 'Oli Ewing', age: 24 },
    { name: 'Aiden Dausch', age: 22 },
    { name: 'Max Brogan', age: 22 },
  ],
  'Southend United FC': [
    { name: 'Collin Andeng-Ndi', age: 24 },
    { name: 'Nathan Ralph', age: 31 },
    { name: 'Ben Goodliffe', age: 25 },
    { name: 'George Wind', age: 24 },
    { name: 'Gus Scott-Morriss', age: 24 },
    { name: 'Noor Husin', age: 27 },
    { name: 'Jack Bridge', age: 29 },
    { name: 'James Morton', age: 25 },
    { name: 'Leon Chambers-Parillon', age: 22 },
    { name: 'Tom Hopper', age: 32 },
    { name: 'Josh Walker', age: 27 },
    { name: 'Anssi Jaakkola', age: 38 },
    { name: 'Harry Boyes', age: 23 },
    { name: 'Joe Gubbins', age: 25 },
    { name: 'Harry Taylor', age: 28 },
    { name: 'Oli Coker', age: 26 },
    { name: 'Sam Austin', age: 25 },
    { name: 'Noah Mawene', age: 21 },
    { name: 'Cav Miley', age: 23 },
    { name: 'Andrew Dallas', age: 24 },
    { name: 'Keenan Appiah-Forson', age: 24 },
    { name: 'Harry Cardwell', age: 27 },
    { name: 'Slavi Spasov', age: 23 },
  ],
  'Stevenage FC': [
    { name: 'Filip Marschall', age: 23 },
    { name: 'Dan Butler', age: 29 },
    { name: 'Carl Piergianni', age: 33 },
    { name: 'Dan Sweeney', age: 29 },
    { name: 'Luther James-Wildin', age: 28 },
    { name: 'Jordan Houghton', age: 28 },
    { name: 'Dan Phillips', age: 26 },
    { name: 'Harvey White', age: 23 },
    { name: 'Dan Kemp', age: 26 },
    { name: 'Tyreece Simpson', age: 23 },
    { name: 'Phoenix Patterson', age: 25 },
    { name: 'Taye Ashby-Hammond', age: 25 },
    { name: 'Lewis Freestone', age: 24 },
    { name: 'Charlie Goode', age: 29 },
    { name: 'Saxon Earley', age: 24 },
    { name: 'Louis Thompson', age: 30 },
    { name: 'Jordan Roberts', age: 29 },
    { name: 'Matt Phillips', age: 34 },
    { name: 'Chem Campbell', age: 22 },
    { name: 'Gassan Ahadme', age: 25 },
    { name: 'Harry Cornick', age: 29 },
    { name: 'Jamie Reid', age: 29 },
    { name: 'Beryly Lubala', age: 27 },
  ],
  'Tranmere Rovers FC': [
    { name: 'Luke McGee', age: 30 },
    { name: 'Patrick Brough', age: 29 },
    { name: 'Jordan Turnbull', age: 31 },
    { name: 'Nathan Smith', age: 29 },
    { name: 'Cameron Norman', age: 30 },
    { name: 'Sam Finley', age: 32 },
    { name: 'Jason Lowe', age: 34 },
    { name: 'Lewis Warrington', age: 23 },
    { name: 'Omari Patrick', age: 29 },
    { name: 'Joe Ironside', age: 32 },
    { name: 'Kristian Dennis', age: 35 },
    { name: 'Jack Barrett', age: 23 },
    { name: 'Ethan Bristow', age: 24 },
    { name: 'Aaron McGowan', age: 29 },
    { name: 'Stephan Negru', age: 22 },
    { name: 'Ryan Watson', age: 32 },
    { name: 'Lee O\'Connor', age: 25 },
    { name: 'Charlie Whitaker', age: 22 },
    { name: 'Sol Solomon', age: 22 },
    { name: 'Connor Jennings', age: 34 },
    { name: 'James Plant', age: 22 },
    { name: 'Jayden Joseph', age: 21 },
    { name: 'Nohan Kenneh', age: 22 },
  ],
  'Walsall FC': [
    { name: 'Sam Hornby', age: 29 },
    { name: 'Evan Weir', age: 24 },
    { name: 'Aden Flint', age: 36 },
    { name: 'Priestley Farquharson', age: 28 },
    { name: 'Connor Barrett', age: 25 },
    { name: 'Brandon Comley', age: 28 },
    { name: 'Charlie Lakin', age: 25 },
    { name: 'Alex Pattison', age: 27 },
    { name: 'Albert Adomah', age: 38 },
    { name: 'Jamille Matt', age: 35 },
    { name: 'Rico Richards', age: 22 },
    { name: 'Myles Roberts', age: 23 },
    { name: 'Mason Hancock', age: 24 },
    { name: 'Harrison Burke', age: 25 },
    { name: 'Vincent Harper', age: 22 },
    { name: 'Jamie Jellis', age: 25 },
    { name: 'Ronan Maher', age: 23 },
    { name: 'Dylan Thomas', age: 22 },
    { name: 'Courtney Clarke', age: 24 },
    { name: 'Aaron Pressley', age: 25 },
    { name: 'Alfie Chang', age: 21 },
    { name: 'Aaron Loupalo-Bi', age: 22 },
    { name: 'Jake Hollman', age: 22 },
  ],
};
